### ISSUE TITLE
Fails to start on Windows 7

### ISSUE THREAD

**Issue by david-schmidt** [fadden/6502bench#1]
I'm getting this when running `SourceGen.exe`:

![screenshot](https://user-images.githubusercontent.com/1110325/46226009-f6b58700-c328-11e8-9337-378d28e463d7.png)

I also had to calm Symantec's nerves about [WS.Reputatoin.1](https://www.symantec.com/security-center/writeup/2010-051308-1854-99?vid=4294919973), but that's to be expected in this nanny state.

**Comment by fadden** [comment]
Hrm.  More assumptions -- I figured Microsoft shoved .net everywhere.

If you do Windows+R and type "dotnet", does it say it can't find anything by that name?  (If it's installed, it'll just pop open a window for a fraction of a second while the shell command runs.)

https://www.microsoft.com/net/download/dotnet-framework-runtime if you want to join the party.

**Comment by david-schmidt** [comment]
No `dotnet` response from Run.  So, installing now - or, it says "do you want to repair or replace 4.7.2?" so maybe I had something on there at one time... we'll see what this gets me.

**Comment by david-schmidt** [comment]
Back from reboot now - Run still can't find a `dotnet`.  Is there another way to query its existence?

**Comment by fadden** [comment]
I posted on stackoverflow and somebody found the problem (https://github.com/fadden/6502bench/issues/3).  I've posted 1.0.0-alpha2 in releases; please give that a try.

**Comment by david-schmidt** [comment]
And we're off!  Thanks!
