### ISSUE TITLE
UI issue - can't define Zero terminated string

### ISSUE THREAD

**Issue by BacchusFLT** [fadden/6502bench#100]
The project uses a JSR to a print routine, which pulls the return address from the stack and uses as pointers to a zero terminated string. Counting up the pointer as it prints, the routine can then push them back in time for the RTS. I have seen this used quite frequently. The good thing is that you don't need to pass a parameter to the print routine.

![image](https://user-images.githubusercontent.com/28536010/127770384-61a3fafa-91ce-4d59-bedf-0f15698c9f27.png)

I need to set the Code Stop at the first address of the string and then code start on the first address after the string zero. I guess this is a corner case, where making the automatic parsing do the job for us is quite tricky.

However, having highlighted the lines as per the picture, the option to select this as a zero terminated string (which it is) is greyed out.

**Comment by fadden** [comment]
Don't use code stop/start points.  Select the data and use Ctrl+H Ctrl+I to mark the whole thing as "inline data" (https://6502bench.com/sgtutorial/inline-data.html).  The code analyzer will step over it.

Better yet, don't do this manually.  Extension scripts (https://6502bench.com/sgtutorial/extension-scripts.html) can mark it as inline data and format the string as well.

I'll need to investigate why the null-terminated string thing isn't working.

**Comment by fadden** [comment]
Try this...

Save the attached file in the same directory as the project.  Then, go to the Project Properties > Extension Scripts tab.  Click "Add Scripts from Project", select file. Click OK a couple times.  Make sure $8763 has the label "PrintString".  Result:

```
+0018e3 98e3: 20 63 87     ??--di?? @T...                 jsr   PrintString
+0018e6 98e6: 20 0d 52 45+          .....                 .zstr pet:“ ”,$0d,“return*continue”,$0d,$91,$91
+0018fb 98fb: 20 e4 ff     ??--di?? ....> L98FB           jsr   GETIN
```

This is immediately applied to all instances of JSR PrintString in the code.

This particular snippet (which I pulled out of the tutorial) applies to all JSRs to any label that *begins* with "PrintString", so "JSR PrintString12" would also be formatted.  This is helpful since there will likely be multiple print-string functions across the different segments of the project.

If you prefer a label prefix other than "PrintString", change the `LABEL_PREFIX` value in the script.

Script: [script.zip](https://github.com/fadden/6502bench/files/6913160/script.zip)

**Comment by fadden** [comment]
The problem with the UI is that it's seeing "invalid" characters in the string, where valid is presently defined thusly:
```
        private static bool[] CreatePrintablePetsciiMap() {
            bool[] map = new bool[256];
            for (int i = 0x20; i <= 0x5b; i++) {
                map[i] = true;
            }
            map[0x5d] = true;
            for (int i = 0xc1; i <= 0xda; i++) {
                map[i] = true;
            }
            return map;
        }
        private static bool[] CreateExtendedPetsciiMap() {
            bool[] map = CreatePrintablePetsciiMap();
            // control codes that we might expect to find in strings
            map[0x05] = map[0x1c] = map[0x1e] = map[0x1f] = map[0x81] = map[0x90] = map[0x95] =
                map[0x96] = map[0x97] = map[0x98] = map[0x99] = map[0x9a] = map[0x9b] =
                map[0x9c] = map[0x9e] = map[0x9f] = true;
            map[0x93] = map[0x12] = map[0x92] = true;
            map[0x07] = map[0x0a] = map[0x0d] = true;
            return map;
        }
```

The string has $91, which appears to be "cursor up".  I could add $91 and $11 to the set, but I'm not sure that's the right approach.

The code is trying to be helpful, but I don't think it's succeeding.  It's calling into a string recognizer function, which I had hoped would automatically spot null-terminated strings "in the wild" someday, so it has to identify a series of bytes as valid string data with a $00 on the end.  In practice, automating that process seems to lead to chaos (null strings, DCI strings, plain strings... easy to set it the wrong way), so I just look for basic strings and leave refinement as a manual step.

One approach would be to make the "extended" PETSCII set include all of $00-1f and $80-9f, although I'm guessing codes like $85-8b (F1-F6) aren't all that useful in a string.  The risk of being overly generous with the character set definition is that it's also used by all of the string-finders, including the automatic one, which could start grabbing things it shouldn't.

I think the best approach is probably to tweak the null-terminated string detector to not fail when encountering "invalid" characters in the string.  You can see from the code pasted in my previous comment (which shows ",$91,$91" at the end of a .zstr) that the code generator handles such strings just fine.

**Comment by BacchusFLT** [comment]
Spot on!

PETSCII string use all sorts of control characters. $08 and $09 are there
to enable and disable between the two character modes (upper/lower and
upper/gfx). You have already identified the cursor movement. You have also
the 16 different ones for setting colour. And reverse on/off control. So
valid Petscii strings can be very rich and I would agree that it's indeed
difficult to be sufficiently helpful. One needs to be perfectly helpful, or
the function risk being a hindrance for manually perfecting it.

/Pontus Berg
 Bergatrollet AB
 CEO & Owner
 Tel/SMS: +46 735 082860
 www.bergatrollet.se


Den sön 1 aug. 2021 kl 20:40 skrev Andy McFadden ***@***.***>:

**Comment by BacchusFLT** [comment]
OK, this is also clear and I have started to adjust it. The inline data
trick is used all over the code - not only for the print, but I do get that
inline data is the way to go, whereby I don't need to stop and then
restart code on either side on the string.

So point taken...

/Pontus Berg
 Bergatrollet AB
 CEO & Owner
 Tel/SMS: +46 735 082860
 www.bergatrollet.se


Den sön 1 aug. 2021 kl 16:38 skrev Andy McFadden ***@***.***>:

**Comment by fadden** [comment]
ABM for the Apple II used inline data for text and all of the math.  Lots of little inlines everywhere.
```
0852: 20 2b 15                     jsr     InS_PrintString   ;print high score notice
0855: c8 c9 c7 c8+                 .zstr   “HIGH SCORE IS ”
0864: 20 73 15                     jsr     InA_LoadFloat     ;copy high score into FAC
0867: 31 0c                        .dd2    high_score
0869: 20 2e ed                     jsr     BAS_PRINT_FAC     ;print FAC
086c: 20 42 15                     jsr     InXY_SetTextPos
086f: 17                           .dd1    23                ;row 23 (bottom of screen)
0870: 00                           .dd1    0
0871: 20 2b 15                     jsr     InS_PrintString   ;print multi-line string (scrolls 3x)
```
Being able to script that saved me a ton of time.

**Comment by fadden** [comment]
Manual string formatting should work in https://github.com/fadden/6502bench/releases/tag/v1.7.5-dev3
