### ISSUE TITLE
Stack table

### ISSUE THREAD

**Issue by BacchusFLT** [fadden/6502bench#103]
One not too uncommon use for vector tables is to have addresses stored -1, so that you can read the addresses from the table and push to the stack, and then call the address with an RTS. 

Selecting the table, choosing Word (CTRL+W) and The Option Address (CTRL+O and Address) followed by "Format Address Table" allows me to make the RTS adjustment (Target -1). So far it does have the feature I want.

There is however a bit of an issue - not all of the selected items turn to be addresses. Three of them look like word values and not addresses.

![image](https://user-images.githubusercontent.com/28536010/127772193-07b68f86-917d-4b01-8f8a-477a22db65dd.png)

Edit: Looking at the first instance, that is a BIT. The entry $8276 aims to call $8277 and that is the LDA hidden by the BIT. I guess this could be a reason for the trouble.

![image](https://user-images.githubusercontent.com/28536010/127772304-6de1faca-baf9-445d-9c51-dae9a7d002bf.png)

**Comment by fadden** [comment]
The Format Address Table feature does not require you to do any formatting beforehand... it's going to rewrite the format on all those bytes.  So you can skip that step.  (https://6502bench.com/sgtutorial/address-tables.html)

Looks like the address in the table is deliberately branching into the middle of an instruction.  When I do it on the same range it looks correct... make sure you check the "tag targets as code start points" box at the bottom of the address table dialog.  (I selected the entire range of bytes and formatted them all at once.)

```
8572: 73 82        L8572           .dd2  T8274-1
8574: d1 82                        .dd2  T82D2-1
8576: 48 82                        .dd2  T8249-1
8578: 61 82                        .dd2  T8262-1
857a: 97 82                        .dd2  T8298-1
857c: 9d 82                        .dd2  T829E-1
857e: 76 82                        .dd2  T8277-1
8580: 1e 82                        .dd2  T821F-1
8582: fd 81                        .dd2  T81FE-1
8584: 76 81                        .dd2  T8177-1
8586: 17 86                        .dd2  T8618-1
8588: d4 86                        .dd2  T86D5-1
858a: 97 89                        .dd2  T8998-1
858c: 2e 82                        .dd2  T822F-1
858e: ea 82                        .dd2  T82EB-1
8590: ae 84                        .dd2  T84AF-1
8592: c7 84                        .dd2  T84C8-1
8594: c9 82                        .dd2  T82CA-1
8596: ac 85                        .dd2  T85AD-1
8598: a9 85                        .dd2  T85AA-1
859a: f7 82                        .dd2  T82F8-1
859c: f4 82                        .dd2  T82F5-1
859e: e0 80                        .dd2  T80E1-1
85a0: 63 81                        .dd2  T8164-1
85a2: 0c 81                        .dd2  T810D-1
85a4: e6 80                        .dd2  T80E7-1
85a6: ee 80                        .dd2  T80EF-1
85a8: 04 81                        .dd2  T8105-1
```
and
```
+002274 8274: a9 00        ??--di?? @T... T8274           lda   #$00
+002276 8276: 2c           n?--diZ? .....                 bit ▼ $01a9
+002277 8277: a9 01        ??--di?? @T... T8277           lda   #$01
+002279 8279: a2 01        ??--di?? .....                 ldx   #$01
```

**Comment by BacchusFLT** [comment]
The middle of the address is the fact that it is used for stack. The
routine takes the data and push it to the stack and does and RTS.

Den sön 1 aug. 2021 17:03Andy McFadden ***@***.***> skrev:

**Comment by fadden** [comment]
I'm not understanding the issue.

Select bytes from +002572 to +0025a9 inclusive.  Actions > Format Address Table.  Check "Adjusted for RTS" near the top and "tag targets as code start points" at the bottom.  As far as I can tell, the results are correct.

The label at $8277 and the other two locations looks like correct behavior, not confusion.  The code is cleverly doing LDA or LDX with an immediate value and then doing a BIT to conceal a second LDA/LDX with a different immediate value.  In the example I pasted earlier, the code at $8279 starts with A-reg set to $00 or $01 depending on how you branched into the code.

![format-table](https://user-images.githubusercontent.com/6185696/127780763-a727b5e3-4929-4d65-870e-c2ce5764d041.png)

**Comment by BacchusFLT** [comment]
The selection is fully correct - the same one I do.

I wasn't aware of the tag in the lower corner, but this is indeed what I
want for the purpose of setting up the table in question.

BasicCommandVectors .dd2 T8274-1      ;/ - LOAD ,8,1
>
>                 .dd2  T82D2-1         ;$ - Directory
>                 .dd2  T8249-1         ;% - LOAD ,8,1 + RUN
>                 .dd2  T8262-1         ;Arrow up - LOAD ,8 + RUN
>                 .dd2  T8298-1         ;Pound - SAVE ,8
>                 .dd2  T829E-1         ;@ - Disk command
>                 .dd2  $8276           ;& - VERIFY ,8,1
>
> The issue is still the $8276 above - that one isn't turning into a label,
but stays being a fixed address. The selection you do above where you force
it to be label -1 and also being a code start locations, and that still
doesn't happen here.

/Pontus Berg
 Bergatrollet AB
 CEO & Owner
 Tel/SMS: +46 735 082860
 www.bergatrollet.se


Den sön 1 aug. 2021 kl 20:04 skrev Andy McFadden ***@***.***>:

**Comment by fadden** [comment]
I downloaded the latest project file from gitlab.  You have three messages at the bottom of the screen about "hidden labels", one for each of the missing links.  So I think the labels got created, but without the "tag targets as code start points" box being checked, the labels ended up in the middle of instructions.  We don't show those, so you get warning messages instead.

In theory, you should be able to just re-do those table entries with "tag targets as code" checked.  In practice, the address table formatter is not adding a code entry point tag if the label already exists.  That's a bug.

You can manually work around the bug in your project by doing what I described in a different issue: mark the instruction above it as a code-stop point, add a code entry point where you see the label, then remove the code-stop.

**Comment by BacchusFLT** [comment]
Many thanks. Looking forward to the future option to redo it then :)

Den sön 1 aug. 2021 23:22Andy McFadden ***@***.***> skrev:

**Comment by fadden** [comment]
Fixed in https://github.com/fadden/6502bench/releases/tag/v1.7.5-dev3

Reformatting the entry now correctly adds a code start tag mid-instruction.
