### ISSUE TITLE
System.ArgumentException: '-59.92*' non è un valore valido per la proprietà 'Height'.

### ISSUE THREAD

**Issue by EmanueleBonin** [fadden/6502bench#108]
I had a crash when opening the program. Looking at the crashlog and then running the debug I found that the problem lay in  SymbolsPanelHeight setter:

rightPanel.RowDefinitions[2].Height = new GridLength(totalHeight - normalized_value, GridUnitType.Star);

so, in order to go on, I put a patch:

               double normalized_value = value;
                if (totalHeight <= normalized_value)
                    normalized_value = 400;
                rightPanel.RowDefinitions[2].Height = new GridLength(totalHeight - normalized_value,
                        GridUnitType.Star);

*** 20/08/2021 08:02:23 ***
  App: 6502bench SourceGen v1.7.5-dev4
  OS: Microsoft Windows 10.0.19042 

System.ArgumentException: '-59.92*' non è un valore valido per la proprietà 'Height'.
Trace:
   in System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   in System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   in System.Windows.Controls.RowDefinition.set_Height(GridLength value)
   in SourceGen.WpfGui.MainWindow.set_SymbolsPanelHeight(Double value) in C:\Documenti\DownLoads\6502bench-master\SourceGen\WpfGui\MainWindow.xaml.cs:riga 500
   in SourceGen.MainController.SetAppWindowLocation() in C:\Documenti\DownLoads\6502bench-master\SourceGen\MainController.cs:riga 482
   in SourceGen.MainController.WindowSourceInitialized() in C:\Documenti\DownLoads\6502bench-master\SourceGen\MainController.cs:riga 254
   in SourceGen.WpfGui.MainWindow.Window_SourceInitialized(Object sender, EventArgs e) in C:\Documenti\DownLoads\6502bench-master\SourceGen\WpfGui\MainWindow.xaml.cs:riga 352
   in System.Windows.Window.OnSourceInitialized(EventArgs e)
   in System.Windows.Window.CreateSourceWindow(Boolean duringShow)
   in System.Windows.Window.CreateSourceWindowDuringShow()
   in System.Windows.Window.SafeCreateWindowDuringShow()
   in System.Windows.Window.ShowHelper(Object booleanBox)
   in System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   in System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   in System.Windows.Threading.DispatcherOperation.InvokeImpl()
   in System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   in MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   in System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   in System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   in System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   in MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   in System.Windows.Threading.DispatcherOperation.Invoke()
   in System.Windows.Threading.Dispatcher.ProcessQueue()
   in System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   in MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   in MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   in System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   in System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   in System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   in MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   in MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   in System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   in System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   in System.Windows.Application.RunDispatcher(Object ignore)
   in System.Windows.Application.RunInternal(Window window)
   in System.Windows.Application.Run(Window window)
   in System.Windows.Application.Run()
   in SourceGen.App.Main()

**Comment by fadden** [comment]
I was able to reproduce the problem by manually changing "main-symbols-height" in the settings file to be larger than the full right-panel window height.

If I make the app window as small as possible vertically, and put a breakpoint in the SymbolsPanelHeight setter, I see value=340 and totalHeight=390.08.  So substituting 400 could still blow up.  I think the best approach is probably to just ignore the saved setting in this case, i.e.:

```
                if (totalHeight > value) {
                    rightPanel.RowDefinitions[0].Height = new GridLength(value, GridUnitType.Star);
                    rightPanel.RowDefinitions[2].Height = new GridLength(totalHeight - value,
                        GridUnitType.Star);
                }
```

This leaves it with a default height.  The ReferencesPanelHeight setter would also get updated.

Do you know how you got into this state?

**Comment by EmanueleBonin** [comment]
I have no idea how how i could fall in that state.

I was decompiling 2 files  in two separated sessions of the program ... could be this behaviour the issue ?

**Comment by fadden** [comment]
I wouldn't expect having two instances to cause a problem.  The settings file is always written in its entirety, so whichever one wrote it last would win.

My best guess at this point is that the window placement function in Windows decided to override the stored position/size with a reduced height.  I could see this happening on a dual-monitor setup if a monitor disappeared and it had to switch to a screen with a different size.

Whatever the case, I think ignoring the stored height values to let the UI reset to defaults should fix the crash.

**Comment by fadden** [comment]
Fix available in https://github.com/fadden/6502bench/releases/tag/v1.8.0-dev1
