### ISSUE TITLE
Enhance long comments

### ISSUE THREAD

**Issue by fadden** [fadden/6502bench#111]
Right now, long comments can be boxed or open, i.e.:

```
***************************
* This is boxed.          *
***************************
```

or

```
;
; This is open.
;
```

Each comment is a contiguous block in the generated sources.  Because comments are associated with file offsets, you can't have two in a row.

What I'd like to do is fake it by having some way to specify that a line should be left totally blank.  For example:

```
; This is comment #1.

; This is also comment #1, but it looks like comment #2.
```

This gives the same aesthetic benefits as having multiple comments, or allowing the user to insert blank lines, without actually changing the way things are put together.

The question is how to specify it.  Once you start down this road, a bunch of other possibilities spring to mind.  For example, we could define a set of embedded codes that would do things like:

- Indicate that a line should be completely blank.
- Start or stop "boxed" mode.
- Specify that a line of asterisks should be printed (currently, in box mode, you just put a '*' on a line by itself).
- Change the width (affects boxing and line-wrap).
- Specify that text is a URL, for the benefit of the HTML exporter.
- Change text or background color, for the HTML exporter.  (I feel like this could go badly for the world.)
- Note that a word is a symbol, so that the refactoring rename updates it automatically when you rename the symbol.

This feels a lot like BBCode, which I'm not overly fond of, but is relatively simple to handle.

-----
Additional ruminations...

Steam game guides use a similar system, with [bracketed]stuff[/bracketed] for formatting.  So it's certainly a proven approach.

For backward compatibility and simplicity we'd probably want to have an "enable fancy formatting" checkbox.  If not checked, you get the old format style.

The refactoring-rename symbol reference is probably the most practically useful thing in the list, since it allows you to discuss symbols without worrying about them getting renamed, but it's also the hardest thing to get right.  The other items are either purely string formatting items, or things that only the HTML converter cares about.

So the BBCode / Steam approach would be:
 - Plain text is just flowed normally.
 - [width=40] sets the line-wrap width to 40.
 - [box] starts a box that maxes out the current line width; [/box] ends it.
 - [boxchar='#'] sets the box character to '#' (default '*').
 - [blank] on a line by itself adds a blank line.
 - [url=example.com]website link[/url], which formats with the URL showing in text output mode, but forms a proper link in HTML output mode.

If we want to get fancy:
 - [symbol]MySym[/symbol] would get updated during a rename.

We currently allow a little flex in assembly source generation, because some assemblers may want to format things a little differently.  For example, some assemblers allow '*' box comments to be on a line by themselves, while others require them to start with a ';', which effectively reduces the line width by one character.  We don't guarantee WYSIWYG.  We may want to force consistency by formatting with the expectation that a leading ';' is required, which would convert an 80-column box to be 79 everywhere.

**Comment by fadden** [comment]
Capturing some notes from e-mail...

> On Wed, Jan 4, 2023 at 11:24 AM Pontus Berg wrote...
> A really easy solution would be to preceed only lines containing text wit the comment marker. So a blank line, would be inserted in the source without the ";". 

That could work.  Anybody who really wants a line with a ';' by itself could make it a space followed by a newline instead of just a newline.  This would only work for long comments that are nothing but blank lines though.  If any additional text appears, it would be treated like a general block comment.  So this:

```
<eol>
blahblahblah<eol>
<eol>
morestuff<eol>
```

would look like:

```
;
; blahblahblah
;
; morestuff
```

rather than:

```

; blahblahblah

; morestuff
```

because I think it looks better to have a consistent comment delimiter for the full height of the block.  To get the blank-line effect in the last one you'd need an explicit "no comment delimiter here" sort of thing like what's described in the bbcode-alike.

There are additional user interaction questions if we add a simple "insert blank line" feature, e.g.: if you do it a second time, does the blank line (a) disappear, (b) remain unchanged, (c) become two blank lines?  It's essentially just an auto-edit of the long comment, so the implementation is straightforward whichever way.

One possible source of user confusion would be over "implicit" and "explicit" blank lines.  Some blank lines are generated automatically, e.g. after an instruction that doesn't continue to the following instruction (JMP, RTS, etc.).  We would have a situation where some blank lines can be altered and some can't, with no clear visual distinction between them. It would show up differently in the "Info" window if you clicked on the line, but I'm not sure if some other minor highlighting effect would be useful.

**Comment by fadden** [comment]
Current proposal:

 - Checkbox determines whether we use "simple" or "fancy" mode for long comments.
 - "Simple" mode output is unchanged.

Fancy mode:

 - Full-comment box-mode is ignored.  Global width sets the initial width.
 - Default comment delimiter is ';', default box delimiter is '*'.
 - Most assemblers don't allow '\*' to start a line; original Merlin actually requires '\*' for full-line comments (the editor shoves anything starting with ';' into the comment column).
 - We want WYSIWYG formatting in the assembled output.  That's currently hampered by the way the box stuff is handled, and potentially by `AppSettings.FMT_ADD_SPACE_FULL_COMMENT`. Boxed output should be shown with the leading ';', unless the box char is ';', in which case we reduce the flow width by one character to get correct Merlin '\*' output.  In other words, the box width is always `line_width-5`, but sometimes we suppress the comment delimiter).
 - Blank lines become blank lines, with no leading comment delimiter.  To get a continuous column of comment delimiters, put a space at the start of blank lines.  (Could have a [noblanks] tag to set the behavior?)
 - The character '[' is used to start a tag.  Escape with backslash, i.e. "\\[".

Fancy mode tags:
 - [width=nn] sets the line-wrap width.  This is the full length of the line, so the actual number of characters will be `line_width-2` to allow a leading '; '.
 - [box]...[/box] puts text in a box.  This can span multiple lines.  The box character can be specified as an option, e.g. [box char='#'].
 - [hr] adds a horizontal line, i.e. a line of characters the full width of the field.  The character can be set, e.g. [hr char='-'].  This will cause a line break if it's not on its own line.  This should work inside a box.
 - [url=example.com]website link[/url] formats a URL.  In text output you see both the URL and the link string, in HTML output you just see the link string.  If the link string is omitted, the full URL will be used for both.
 - [sym]symbol[/sym] identifies a symbol.  The goal is to have this updated during a refactoring rename.  In HTML output we can make this a link to the symbol definition.

Tags for character style (bold/italic), size, and color are possible but are only of value for HTML output.  Skip those for now.

Fancier structures, like numbered and unordered lists and tables, are of limited value.  Skip.

**Comment by fadden** [comment]
Available in https://github.com/fadden/6502bench/releases/tag/v1.9.0-dev3

**Comment by BacchusFLT** [comment]
I still don't get setting character for for box to work, it works for hr. I
guess non sensitive to white space and support for both ' and " would
likely dodge user issues here.

I was tinkering more with fancy formatting and found that there are cases
where I didn't get it to work as expected.

[hr] provides a horizontal row of "-"
If I add a box and add inside the box add a [hr], that row is using the
standard character for the box
If I add a [hr] after the box, the default character reverted to the
default outside of the box

Setting a [hr] inside a box works, but a hr char does not.

[br] inside a box also failed for me.

[hr] has a space between the ";" and the first character. For boxes there
is no such space.

/Pontus Berg

Den ons 29 juli 2026 kl 16:27 skrev Andy McFadden ***@***.***
