### ISSUE TITLE
LO/Hi parsing

### ISSUE THREAD

**Issue by BacchusFLT** [fadden/6502bench#120]
One of the thing that exists in all projects is this:

L0904           lda   #$b6            ;2
                sta   $fffe           ;4
                lda   #$09            ;2
                sta   $ffff           ;4

That is setting a vector to point to an address - in this case $09b6.

You can manually do
Create [label]
Set the #$b6 (CTRL+O) to point to Symbol [label] with lo
Set the #$09 (CTRL+O) to point to Symbol [label] with hi

I realise there a number of permutations to this (like "low first to hi first", using "lda, ldx, sta, stx" and so on) but it might just be too common not to have a look at special treatment of it, and the manual option is quite cumbersome (possible, but cumbersome).

**Comment by BacchusFLT** [comment]
Already when doing CTRL+O, there wouldn't really be any need to select LO/HI unless the LO and HI are the same. It should be evident if I select a symbol for an existing label if I mean low or hi if the current byte corresponds with lo or hi for that label.

**Comment by fadden** [comment]
Something like this would likely be done as a separate "multi-edit" action, like address table formatting.  You'd select a set of lines that included two immediate loads, and then invoke the action, which would query for a symbol name.  It could figure out what it thought was the right answer, and allow the initial guess to be overridden.  Ideally it would be able to guess at the symbol by combining immediate operands.

Related: issue #21 discussed the idea of recognizing these patterns automatically for "known" vector targets.

**Comment by BacchusFLT** [comment]
Yes, I see now that my suggestion is totally redundant - it's very much the same thing as suggested in issue #21.

**Comment by fadden** [comment]
Not totally redundant: the previous issue was asking for automatic formatting, based on marking external addresses as vectors.  Scanning the code for patterns and formatting automatically could be tricky, and would require a way to manually undo the automatic behavior when it got it wrong.  The idea here would be more like a "power user" macro feature, where the target would be selected manually.  It has general applicability to any pair of immediate load instructions used to set up a pointer.

**Comment by fadden** [comment]
Moved to "TO DO" wiki.
