### ISSUE TITLE
OMF converter crashing

### ISSUE THREAD

**Issue by ERolfi** [fadden/6502bench#124]
When trying to convert MUSIC.SYS16 program, there is a crash in version 1.8.0 and above.

It was working correctly up until version 1.7.5

[MUSIC.zip](https://github.com/fadden/6502bench/files/8425823/MUSIC.zip)

**Comment by fadden** [comment]
Looks like a bad interaction between the OMF converter and the address-map code that got rewritten in 1.8.  I'll dig into it today.

**Comment by fadden** [comment]
Should be fixed here: https://github.com/fadden/6502bench/releases/tag/v1.8.3-dev1

The project generated by v1.8.3-dev1 for MUSIC.SYS16 matches that generated by v1.7.5, except for the header comment (which includes the version number) and the address map.  The address map is functionally identical -- a series of "floating" regions -- but the serialization changed to allow for the new bells and whistles.  (If you load the v1.7.5-created project into v1.8.x and save it, you get the same result.)

**Comment by ERolfi** [comment]
Very well. It seems to work as expected now. Thank you.
