### ISSUE TITLE
Suggestion: Keyboard shortcuts customization

### ISSUE THREAD

**Issue by grue74** [fadden/6502bench#135]
I live in Finland and I use Finnish variant keyboard where semicolon ";" key is accessed by pressing "shift + ," which is assigned to add comment function.
I cannot access that shortcut with Finnish keyboard layout. Fortunately I can switch input profile in Windows quite easily, and then I can access ";" by pressin "Ö" key on my keyboard.

So, customization for keyboard shortcuts are needed.

**Comment by fadden** [comment]
I use a "TO DO" wiki for feature requests: https://github.com/fadden/6502bench/wiki/TO-DO-List

This is currently listed as "Add configurable hot-keys".  I updated it with a reference here to note the importance for non-US keyboards.
