### ISSUE TITLE
Failed to open project file larger than 2MiB

### ISSUE THREAD

**Issue by absindx** [fadden/6502bench#137]
Thank you for the great software.  
I will report on my friend's findings instead.  

`JavaScriptSerializer` is limited to string length equivalent to UTF-8 2MiB by default.  
It checks if the JSON string fits within `JavaScriptSerializer.MaxJsonLength` and throws an exception if it exceeds. (Default value is `DefaultMaxJsonLength = 2097152`)  
https://referencesource.microsoft.com/#System.Web.Extensions/Script/Serialization/JavaScriptSerializer.cs,76352a505a3d40a3,references  

When outputting a file, line break is added after braces and commas,  
but if this process exceeds 2MiB, a "project file that could be saved but cannot be opened" is created.  

https://github.com/fadden/6502bench/blob/58d794f5354c6d250c999f2690e4c7cc63731ac9/SourceGen/ProjectFile.cs#L68-L78  

SourceGen can currently open and analyze files as large as 1MiB,  
so adding tags and comments to the whole area is likely to hit the limit.

**Comment by fadden** [comment]
Ugh.  Super Mario Bros is only 32KB + graphics, and the .dis65 is about a megabyte, so this is a concern for projects much smaller than a megabyte.

Looks like the max can be trivially overridden with the MaxJsonLength property.  It might also be time to move to a different implementation (maybe https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializer?view=net-7.0 ?)  I'm not quite ready to let go of JSON though... it's not the most efficient way to store things, but it has worked well so far.

Was this discovered by failure or by code inspection?

**Comment by absindx** [comment]
Discovered by failure.
My friend disassembled a 512KiB SNES program and added a lot of bulk labels to the compressed data.

**Comment by fadden** [comment]
Should be working in v1.8.4-dev2.  Cap is now 64MB.  I tested it with a 9.5MB .dis65 (attached here for future reference).

[bigfile.zip](https://github.com/fadden/6502bench/files/10354106/bigfile.zip)
