### ISSUE TITLE
Project symbol

### ISSUE THREAD

**Issue by BacchusFLT** [fadden/6502bench#138]
Adding a project symbol, you can add a size for it. If I enter a label I can set types, but I cannot define that it's a start of a segment.

Wouldn't it be handy to stand on an address and then implement a project symbol starting on that address?

**Comment by fadden** [comment]
Project and platform symbols are intended for "external" addresses, outside the scope of the file.  For something like the text screen, or a file buffer that lives at a fixed address, you can specify the size of it so that references to Symbol+25 get resolved automatically.

For internal structures, you specify the length by giving it a data operand of the desired length, e.g. by selecting the region and using the "uninitialized data" bulk data option.

One thing you can't do with the current scheme is define overlapping structures inside the file.  With project/platform symbols you can define a 32-byte buffer ("saved_game_state") and then have different symbols for various bytes within it ("current_level", "current_hp", etc).  There's no equivalent way to do that with labels.

What are you trying to do?

**Comment by BacchusFLT** [comment]
In this case I had several instances of graphics inside the program. It is copied to the destination in copy loops and I would like to have the Symbol+offset behaviour for the copy loops.

Eg a multicolour font is a chunk of data. I set a label at the start, but then the copy loop would create a new label on even $100 intervals rather than setting the start with an offset.

The data is initialised.

                lda   Font_MultiColour,x ;4+
                sta   $e000,x         ;5
                lda   L3900,x         ;4+   // This one I would have wanted to be Font_MultiColour+$100,x
                sta   $e100,x         ;5
                lda   L3A00,x         ;4+ // This one I would have wanted to be Font_MultiColour+$200,x
                sta   $e200,x         ;5
                lda   L3B00,x         ;4+ // This one I would have wanted to be Font_MultiColour+$300,x
                sta   $e300,x         ;5
                dex                   ;2
                beq   L40C2           ;2+

**Comment by BacchusFLT** [comment]
I also just had the opposite situation;

In a block of bytes where the program stores the status for things it does, the respective bytes had individual and automatically generated labels. When I changed the first one, the three subsequent ones were removed and replaced with offsets in the code. 

Here I wanted the "scope of the label" to be only that one byte.

**Comment by fadden** [comment]
If `Font_MultiColour` is defined as a single block (e.g. "densely-packed bytes" or "uninitialized data"), the LDA lines will get formatted automatically.  If that's not an option, e.g. you want to limit the bytes per line in the assembly, then you would need to set the operand on every LDA line to reference `Font_MultiColour` as a symbol.  The address adjustment will be applied automatically.

The label-finder needs some way to know that it should associate the LDA operand with the label.  If the target address falls inside a data format area, it'll figure that out.  If not, we'd need some other mechanism to say, "everything that refers to this zone should map to this one label".

With regard to adjacent labels being combined, try Edit > Project Properties, General tab, un-check "Seek nearby targets".  From the reference manual:

> If seek nearby targets is checked, the analyzer will try to use nearby labels for data loads and stores, adjusting them to fit (e.g. LDA LABEL+1). If not enabled, labels are not applied unless they match exactly. Note that references into the middle of an instruction or formatted data area are always adjusted, regardless of how this is set. This setting has no effect on local variables, and only enables a 1-byte backward search on project/platform symbols.

My experience has been that the feature is either really useful or really annoying, depending on the nature of the project.  It's a project-specific property, so you can have it on for one and off for another.  I occasional debate with myself whether it should default on or off.

**Comment by fadden** [comment]
Added "area labels" to ["TO DO" wiki](https://github.com/fadden/6502bench/wiki/TO-DO-List).

**Comment by BacchusFLT** [comment]
Humble thanks.

Den tors 2 feb. 2023 02:12Andy McFadden ***@***.***> skrev:
