### ISSUE TITLE
Fails on Wine, with .NET 4.6.2 installed

### ISSUE THREAD

**Issue by dylanmc** [fadden/6502bench#14]
Crash message is:

wine: Call from 0x7b42c637 to unimplemented function api-ms-win-core-winrt-roparameterizediid-l1-1-0.dll.RoGetParameterizedTypeInstanceIID, aborting
wine: Call from 0x7b42c637 to unimplemented function api-ms-win-core-winrt-roparameterizediid-l1-1-0.dll.RoGetParameterizedTypeInstanceIID, aborting
wine: Call from 0x7b42c637 to unimplemented function api-ms-win-core-winrt-roparameterizediid-l1-1-0.dll.RoGetParameterizedTypeInstanceIID, aborting
wine: Unhandled exception 0xe0434352 in thread 2b7 at address 0x7b42c637 (thread 02b7), starting debugger...

Maybe there's another dependency besides .NET?

**Comment by fadden** [comment]
SourceGen is entirely C# .NET -- no native or unsafe code.

The goal is to have it be executable directly from Linux and Mac OS X.  If you have the latest version of Mono installed you can just run "SourceGen.exe" from the Linux command line.  Unfortunately, with 1.0,0-alpha2 you'll get a failure message from my code, followed by a crash; with tip-of-tree sources you'll get a crash in the WinForms code that needs investigating.  (Tested under Ubuntu 16.04.)

I don't know enough about .NET or Wine to guess at why it doesn't work there.

**Comment by fadden** [comment]
Wine and .NET don't seem to get along.  WinForms had too many problems (see issue #31).

There really isn't a good cross-platform C# GUI toolkit right now.  My hope is to use something like Avalonia once it matures.  The transition to WPF makes the Windows experience a bit better, and should ease the transition to anything XAML-based.

**Comment by iolo** [comment]
I succeed to run in wine.

```
winetricks d3dcompiler_47
```

**Comment by dylanmc** [comment]
Just now I was able to run it in Crossover with default settings - which is great!
