### ISSUE TITLE
String length

### ISSUE THREAD

**Issue by BacchusFLT** [fadden/6502bench#140]
Selecting a string operand, I would seek an option to select the string lengths.

My scenario here is a big block of text that form a screen, which means I would like to see that the strings are 40 chars long (one string = one screen row).

**Comment by fadden** [comment]
There's currently no length-limiter on string selection.  The best you can do right now is:

1. Select full block.
2. In the "Bulk Data" section of Edit Operand, select "Densely-packed bytes" with a limit of 40 bytes per line.  This splits lines at the appropriate boundaries.
3. Put labels at the start of every line (`@line0`, `@line1`, ...).
4. Select the full block and format it as a string.  The labels cause the formatting to be split.

Not great.  To make this easier I think we'd need to generalize the "bytes per line" restriction.  It's not part of the operand format descriptor; the dialog just uses it to generate multiple separate formatters.  So making bytes-per-line apply more generally shouldn't pose a problem.

(Note to self: the dialog currently dislikes treating single bytes as strings, which would be an issue if you (say) selected 81 bytes and tried to format 40 per line.  It rejects the entire set.  Need to fix that.)

**Comment by BacchusFLT** [comment]
Sounds great! Humble thanks.

Den tis 31 jan. 2023 21:17Andy McFadden ***@***.***> skrev:

**Comment by fadden** [comment]
Added "generalize max-byte-per-line" feature to ["TO DO" wiki](https://github.com/fadden/6502bench/wiki/TO-DO-List).
