### ISSUE TITLE
Address table pointing to region

### ISSUE THREAD

**Issue by BacchusFLT** [fadden/6502bench#141]
As described before, it's common on the c64 to have drive code in the computer and then send it over to the drive. Given that the drive code is executed in the other location, it's handy to use the region feature.

Once the code is sent, it's normally so that the area is available for other purposes. In the case at hand, the place is the location for bitmap which is going to be manipulated. There is a table that point to different parts of the bitmap (one table of lowbytes and one table of highbytes). Normally 6502 bench handle them beautifully, but it seems the region definition messes things up. It seems not possible to have the table point at the address occupied by a region.

![image](https://user-images.githubusercontent.com/28536010/215855273-35a07ba3-8ff4-4db9-aba0-d6dafb2418a1.png)

**Comment by fadden** [comment]
If I understand the situation correctly, the problem is that the address range in question is effectively not included in the file.  It can't put a label on those addresses because the file doesn't cover that address range... the bytes there are getting put somewhere else, so there's nowhere to hang a label.

One hackish way to work around the issue would be to artificially extend the binary and "patch in" the extra bytes to fill the gap.  That just seems wrong somehow. :-)

**Comment by BacchusFLT** [comment]
It is included in the file, but 6502 bench might not see it that way as
it's part of a region that has a different start address.

Den tis 31 jan. 2023 22:18Andy McFadden ***@***.***> skrev:

**Comment by fadden** [comment]
Everything works off of file offsets.  The byte at +002ec2 was initially at $32c0, but got relocated elsewhere.  As far as SourceGen is concerned, the file has a gap in the middle where the code used to live... there is no byte in the file that corresponds to address $32c0.

We'd need a way to put two different labels at +002ec2, one "pre-move" and one "post-move", which SourceGen doesn't know how to do (except for the address region pre-label mechanism, but that won't help much here).

**Comment by BacchusFLT** [comment]
Exactly. I solved it by removing the definition of drive code and the
region, calling it uninitialized data. Then I exported the segment and
handled it separately. A separate reassembly. Not optimal but handled the
situation.

But it seems my initial thought was correct. The absolut address of the
file is no longer associated with a logical address, and the reassembly
works with the logical addresses, right?

Den tors 2 feb. 2023 02:11Andy McFadden ***@***.***> skrev:

**Comment by fadden** [comment]
You are correct.

This felt familiar, so I went back and found a variation of this in issue #130.  There's a "TO DO" item about having the address table formatter work with project/platform symbols, which could be used here... defining a project symbol that spanned the gap would give the formatter something to work with.
