### ISSUE TITLE
Working with Symbols

### ISSUE THREAD

**Issue by grue74** [fadden/6502bench#148]
Hello, I had a project with multiple files, and they all used zero-page addresses to transfer information to each other.

When I made symbols for program one, I couldn't transfer these to program two, and so on.

I kludged my way out of this by creating a project .sym64 file under runtimedata directory, but I felt bad about that as I couldn't think of any other way around this limitation.

I also felt quite uncomfortable that I had to manually mark every symbol as exportable when transferring common routines to every puzzle piece. How about setting in the project settings to ensure all symbols are exportable? I used the search & replace function in my text editor for this...

6502bench has been my top tool in my reversing hobby! Keep up the good work!

**Comment by fadden** [comment]
This is an area that SourceGen doesn't handle well.  The "Working With Multiple Binaries" section in the manual notes:

> Support for this is currently somewhat weak

There are two approaches, both of which you found.

 1. Create a shared .sym65 file, and manually edit it as symbols are found.  This works, but is a little tedious to maintain.  (File > Reload External Files can be helpful here.)  I used this for Stellar 7, which has pieces scattered across half a dozen files, and wasn't especially happy with it.
 2. Mark symbols as "export", and use the "import symbols" feature to pull them in as project symbols for other binaries.  This is what the "export" flag on symbols is intended to do, but the manual import step is undesirable.  The existing feature is something of a kluge.

Having a higher degree of automation on these would help quite a bit.  For example, it would be useful for a project to keep track of other projects from which symbols are imported.  When the project is opened, SourceGen could check the modification dates on the other project files, and put up a "re-import symbols?" dialog that would pull the symbols across.

Some other things would be needed, like:

- Managing updates when both projects are being edited simultaneously.
- Removing symbols that were removed from the other project.  The current "import" feature just drags in new stuff.

I think the issues come back to one basic problem: the current system isn't "live" enough.  It's not sharing information in real time.  We don't actually want to store the shared bits in a .sym65 or in the project symbols table of other projects; we want to define them in one place and have the other projects see changes immediately and not store them internally.  (The latter means that the project files would break a little if they weren't distributed together, but that's true of existing .sym65 / .dis65 / binary file sets anyway.)

Such an arrangement brings up other issues, like what to do if the same symbol is exported from multiple files but with different values.  The difficulty there is mostly in the amount of work required to present coherent information to the user and provide UI elements for managing the conflicts.

The current implementation was not intended to be the real solution.  I wasn't sure what the best approach was going to be, so I threw the current stuff together to get a feel for how it would work.  Unfortunately I never got around to designing a better system.  What's there now is less "broken feature" and more "missing feature".

Re: export-all.  That's easy enough.
