### ISSUE TITLE
crash when setting origin and code start point for attached binary

### ISSUE THREAD

**Issue by robjustice** [fadden/6502bench#150]
I'm getting a crash when trying to disassemble the attached file. Its an Apple3 Interpreter binary.

They have a header as follows:
8 bytes Label, always - "SOS NTRP"
2bytes - option header length. Most of the time this is zero
2 bytes - loading address
2 bytes - code length
Then the code starts

[SOS INTERP - Easyterm.zip](https://github.com/fadden/6502bench/files/11438081/SOS.INTERP.-.Easyterm.zip)

![screencapture](https://github.com/fadden/6502bench/assets/18372125/c7269ce8-69b6-47d6-8167-e2cc514d746a)

the attached one is loaded at $6000. When I set the origin to $5ff2 (to account for the header length), and then try to indicate the code start point at $6000, I get a crash and Sourcegen closes.

I'm using version 1.8.4

 
[CrashLog.txt](https://github.com/fadden/6502bench/files/11438091/CrashLog.txt)

**Comment by fadden** [comment]
Can you provide the binary that goes with the project file as well?  I tried to replicate the crash with a different SOS binary but was not able to.  According to the crash log, the crash is happening at the tail end of editing an address region.  The change has been made, but when SourceGen tries to regenerate the listing it crashes (null pointer deref).

FWIW, the best way to format a file with an OS header is to use two adjacent regions, with one that covers just the header and one that spans the rest of the file.  Mark the one that covers the header as "non-addressable" (type "NA" in the address box).

**Comment by fadden** [comment]
If I disable auto-formatting of $CA (READ) parameter blocks, the crash doesn't happen, revealing that the disassembly is:
```
6307: 04           L6307           .dd1  $04
6308: 00           L6308           .dd1  $00
6309: e2                           .dd1  $e2
630a: 62                           .dd1  $62
630b: 01                           .dd1  $01
630c: 00                           .dd1  $00
630d: 00                           .dd1  $00

630e: 00 ca        L630E           brk   SOS_READ
6310: 07 63                        .dd2  L6307
```
According to the SOS reference manual, the parameter block should be 8 bytes long:
```
 +$00 param count
 +$01 ref_num
 +$02 data_buffer
 +$04 request_count
 +$06 transfer_count
```
However, there's only room for 7 bytes, which means the BRK instruction is getting overwritten on every call.  The only reason the code works is because the transfer count is a single byte, so it's always writing zero into the high byte of the count.  (Bug? Cleverly saving one byte? Who knows.)

SourceGen is getting confused because the BRK instruction is getting re-formatted as inline data when the parameter block gets formatted.  The code that was supposed to prevent scripts from doing that had a bug.  With the fix I get:

```
6307: 04           L6307           .dd1  4
6308: 00           L6308           .dd1  0
6309: e2 62                        .dd2  L62E2
630b: 01 00                        .dd2  $0001
630d: 00                           .dd1  $00

630e: 00 ca        L630E           brk   SOS_READ
6310: 07 63                        .dd2  L6307
```

**Comment by robjustice** [comment]
Thanks, that's working great for me now. I'm sure your right, its only ever looking to grab one char at a time from the serial port, so would never get overwritten with too big a transfer count. Probably an oversight. Thanks for digging into it and sorting it out. I was just trying to understand the behavior for this terminal program, so started down the disassembly route to see what's going on.

And thanks also for explaining the NA address region, and how to show the high level address map. That's quite nice..
