### ISSUE TITLE
Renamed .dis65 files cannot be reopened

### ISSUE THREAD

**Issue by c64cryptoboy** [fadden/6502bench#155]
Got a bug that's easy to reproduce:  If I save a file, then do a "save as" with a different filename, the two project files' content are identical, yet the new file cannot be opened in 6502bench (unless changed back to the original filename).  If I select the renamed file to open, it will say "the file doesn't exist", and ask "Do you want to locate the data file?", if I select OK and select it again, the next time it will complain that the file is the wrong number of bytes.  If you update the number of bytes in the project file manually, then it complains about the CRC, etc.

**Comment by fadden** [comment]
There is no link between the .dis65 file and the data file it is operating on; they're assumed to have the same name.  If you rename the .dis65 file, you must also rename the data file.  (No part of the original binary data file is included in the .dis65 file.  This is primarily to avoid copyright infringement... the .dis65 file can be shared even when the binary file can't.  The binary is re-loaded every time you open the .dis65 file.)

When it asks to find the data file, make sure you're selecting the binary data file and not the .dis65 file.  If the number of bytes or the CRC don't match, it's a strong indication that the .dis65 file is not paired with that data file.

I have a set of tests (https://github.com/fadden/6502bench/tree/master/SourceGen/SGTestData/FunkyProjects) where multiple .dis65 files share a single data file.  These appear to be working.

**Comment by c64cryptoboy** [comment]
Ah, this was a lack of understanding on my part; there's no bug here.  Thanks for the quick reply (and for this great tool!).
