### ISSUE TITLE
Hide implicit accumulator argument

### ISSUE THREAD

**Issue by ksherlock** [fadden/6502bench#162]
I noticed that merlin32 generates an operand for implied accumulator instructions (`SuppressImpliedAcc = false`)

While Merlin (8/16/32) allow it, it is -- to quote the Merlin 8/16 User's Manual, page 84 -- considered perverse:

> NOTE: The accumulator Mode does not require an operand (the letter "A"). For example, to do an LSR of the accumulator, you can use:
> ```
> 1    LABEL   LSR                ; LOGICAL SHIFT RIGHT
>```
> Some assemblers perversely require you to put in "A" in the operand for this mode.
>
> Merlin 8/16 will decide the legality of the addressing mode for any given opcode.

**Comment by fadden** [comment]
Right now `SuppressImpliedAcc` is only true for ACME, which disallows them.

I may be perverse, but I kinda like having it there. :-)  Some other Apple II assembler (Orca/M?) required it.

It could be made a tri-state tunable parameter (prefer on, prefer off, no preference).

**Comment by ksherlock** [comment]
Yesh, ORCA/M (perversely) requires the explicit A.

**Comment by fadden** [comment]
Setting is available in v1.9.1-dev1.  It affects on-screen display, generated assembly, and the instruction chart.
