### ISSUE TITLE
There are no C64 platform symbols

### ISSUE THREAD

**Issue by AgentFriday** [fadden/6502bench#19]
Not sure if they don't yet exist, or if I just don't know how to use the tool... but I'm not sure how to get common C64 platform symbols to be recognized in the disassembly.

**Comment by AgentFriday** [comment]
I definitely see the value to separating symbols into multiple files, since each project will use existing platform definitions to varying degrees...  Some may use only the Kernal, some will interoperate with BASIC, and others will use neither.

I'll see if I can find the time to contribute some symbols files.  I can at least contribute some sparse tables that would be deemed worthwhile...  until such time as someone provides something more complete?

**Comment by AgentFriday** [comment]
It seems that it would be nearly impossible to correctly deduce non-address symbols...  It's neat that the format allows for these but I'm guessing that it just isn't going to be useful at the platform level, and that the intended use for non-address values was for symbols specified interactively.

Let me know if I'm missing any significant uses at the platform level...

**Comment by fadden** [comment]
Correct, constants exist for things like `LDA #$41` where it's unlikely that just grabbing a constant with the same value will be what you actually want.

If you look at the Apple II stuff you'll notice an automated usage.  The [ProDOS 8 script](https://github.com/fadden/6502bench/blob/master/SourceGen/RuntimeData/Apple/ProDOS8.cs) is looking up symbols with the `ProDOS8-MLI-Functions` tag.  This is defined in the [ProDOS 8 sym file](https://github.com/fadden/6502bench/blob/master/SourceGen/RuntimeData/Apple/ProDOS8.sym65).  The tag mechanism allows extension scripts to apply constant symbols from a specific set to things.

Similar things are used for GS/OS inline calls and Apple IIgs toolbox calls (which replace a `LDX #$nnnn` that comes before the JSL with `LDX #symbol`).

Even if it doesn't make sense to apply them automatically they could still come in handy, but the person doing the disassembly would have to know that they were there.  The Symbols window can be configured to show only platform constants, so it's not a total guessing game, but it's not especially convenient.

At the end of the day these files are loaded at runtime, so they can be updated and distributed outside the normal release cycle, and anybody who doesn't like them can easily hand-edit their own copy.  So if you don't see an obvious need for something, skip it, and we can always throw it in later.

**Comment by fadden** [comment]
There's not a lot, but there's no longer none.
