### ISSUE TITLE
Fails to run in Windows 10 pro

### ISSUE THREAD

**Issue by Charlie-2** [fadden/6502bench#2]
From Event Viewer Application log:

Faulting application name: SourceGen.exe, version: 1.0.0.0, time stamp: 0x5bae6108
Faulting module name: comctl32.dll, version: 6.10.17134.285, time stamp: 0xa16245d4
Exception code: 0xc00000fd
Fault offset: 0x00053fd7
Faulting process id: 0xcac4
Faulting application start time: 0x01d45757732bb412
Faulting application path: C:\Users\charl\Downloads\6502bench100a1_debug\SourceGen.exe
Faulting module path: C:\WINDOWS\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.17134.285_none_42efceba44e1907b\comctl32.dll
Report Id: db5c6643-df38-481d-988f-cfe8d548530f
Faulting package full name: 
Faulting package-relative application ID:

**Comment by fadden** [comment]
Ugh. Can you try the Release version in case that makes a difference?

.NET is not working out as well as I'd hoped. :-(

**Comment by Charlie-2** [comment]
Additional info:

The Release version does essentially the same thing:
Note they are both complaining about the comctl32.dll.
---
Faulting application name: SourceGen.exe, version: 1.0.0.0, time stamp: 0x5bae610f
Faulting module name: comctl32.dll, version: 6.10.17134.285, time stamp: 0xa16245d4
Exception code: 0xc00000fd
Fault offset: 0x00053fd7
Faulting process id: 0x106ac
Faulting application start time: 0x01d45757334d43e8
Faulting application path: C:\Users\charl\Downloads\6502bench100a1\SourceGen.exe
Faulting module path: C:\WINDOWS\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.17134.285_none_42efceba44e1907b\comctl32.dll
Report Id: 3727f89b-5964-4b14-8219-059ba55564a1
Faulting package full name: 
Faulting package-relative application ID: 
---

running 'dotnet --version' from the command prompt shows 2.1.103
Attempting to install '.NET Framework 4.7.2' says it is already installed.

**Comment by Charlie-2** [comment]
The 'comctl32.dll' thing has been nagging my memory.  I think I had this problem with a project a while ago.
I had to add **Comctl32.lib;** to the list of Additional Dependencies for the Linker.
That's **Configuration Properties - Linker - Input - Additional Dependencies** in Visual Studio 2017.

**Comment by fadden** [comment]
I posted on stackoverflow and somebody found the problem (https://github.com/fadden/6502bench/issues/3).  I've posted 1.0.0-alpha2 in releases; please give that a try.

**Comment by Charlie-2** [comment]
Okay, both the release and debug version (1.0.0-alpha2) now run.
