### ISSUE TITLE
Decide on a set of mnemonics for undocumented 6502 opcodes

### ISSUE THREAD

**Issue by fadden** [fadden/6502bench#20]
cc65, 64tass, and SourceGen have very similar mnemonics for the undocumented 6502 opcodes, but all three are slightly different.  I'd like to pick one set.  This doesn't matter too much -- SourceGen will remap the mnemonics to whatever the target assembler wants -- but it does affect what you see in the code list on screen.

Besides, after 40 years, we really ought to settle on something.

(The Apple II community doesn't do much with these, because the //c, enhanced //e, and IIgs use the 65C02 or 65816, so any code that uses the instructions would be limited to older computers.  Consequently I don't really have an opinion.  Well, I prefer HLT to JAM, but I'll get over it.)

My current inclination is to use the set defined by 64tass, since their documentation seems pretty thorough.  If there's a "standard" set that some notable group of people have agreed on, a pointer to it would be helpful.

**Comment by oziphantom** [comment]
Unintended Opcodes are deeply entrenched in the DemoScene realm, to which the C64 community is the strongest. This is the definitive document on them https://csdb.dk/release/?id=161035 written by Groepaz who is one of the main people in the VICE emulator team. Its the source and behavior we all refer to. So I guess its names are the "standard", although it documents all names known for each opcode. I would expect Soci (author of TASS) to follow this naming convention, but I've not checked 100%.

**Comment by fadden** [comment]
Scanning through the docs...

$4B: ALR (UO, cc65), ASR (64tass)
$9B: TAS (UO, cc65), SHS (64tass)
$BB: LAS (UO, cc65), LDS (64tass)
$CB: SBX (UO, 64tass), AXS (cc65)
$E3 (et. al.): ISC (UO, cc65), ISB (64tass)

64tass does accept the UO versions as aliases, so they can all be used without remapping.  UO acknowledges most of the aliases, except LDS.

Let's go with the UO version.
