### ISSUE TITLE
Automatically recognize load address at beginning of C64 platform files

### ISSUE THREAD

**Issue by AgentFriday** [fadden/6502bench#23]
Don't know if Atari or Apple file formats are recognized, but for C64 it's pretty universal and simple...  First 2 bytes are a little-endian word, directly followed by code hint.  If it's a false assumption, it will probably generate some tell-tale signs...

**Comment by fadden** [comment]
The long-term answer is what I've been calling "file format recognizers", in which an externally-defined script gets to see the file name and contents, and applies various attributes.  Some Apple II utilities store file meta-data in the filename ([like this](https://nulib.com/library/nulib2-preserve.htm)), which is how the load address for binaries gets preserved.

We can do something much simpler (and much sooner) for this though.  The platform definitions include an array of name-value pairs that are used for things like "include undocumented opcodes" and "default load address".  We could add one that just says, "load address is in first two bytes".  The method that applies the system definition is called after the data file is loaded, so it has the necessary information at hand.

I'll define "first-word-is-load-addr" as a boolean, and if it's true do the appropriate thing.

**Comment by fadden** [comment]
A file with this:

    000000: 00 40 ea 60

Turns into this:
```
                         .org    $3ffe
3ffe: 0040               .dd2    $4000

4000: ea                 nop
4001: 60                 rts
```
Does that look right?

**Comment by fadden** [comment]
Nope, that's wrong too... now it thinks there's a label at zero-page address $00.  I kind of want a "this has no address" directive.

**Comment by fadden** [comment]
Take three:
```
                         .org    $4000
4000: 0040               .dd2    $4000

                         .org    $4000
4000: ad0040    L4000    lda     L4000
4003: 60                 rts
```
Overlapping address spaces are supported, so this will *usually* do the right thing.  If it doesn't, it's easy enough to edit by hand.

**Comment by AgentFriday** [comment]
Yeah, I was grapplying for something that didn't assign any address to the first two bytes as well.  If an address must be assigned, I kinda think stuttering on the load address is the best option.  Backing up 2 bytes is something I've seen at least 2 other tools use, and I can't really find anything fatal about it either...
