### ISSUE TITLE
Move to Undo position before undoing (or redoing)

### ISSUE THREAD

**Issue by AgentFriday** [fadden/6502bench#25]
It's really hard to know what's being undone if it's happening off-screen...

I personally **really, really** appreciate editors that make sure you are viewing the undo location before performing it, otherwise it's hard to see what's been undone (you just see the after, not the before...)  This would follow an algorithm  something like:

    auto lastEdit = undoStack.pop();
    if (lastEdit.isVisible())
        lastEdit.undo();
    else
    {
        lastEdit.positionTo();
        undoStack.push(lastEdit);
    }

Doesn't hurt to ask, right?  ;-)

**Comment by fadden** [comment]
There is a counter-argument to this: sometimes the thing you do at address A, such as defining a label or code hint, can have an effect at address B.  If you want to hit undo/redo while watching address B, you can right now.  This is fundamentally different from a source code editor, where changes are always local.

I'm wondering if an explicit "jump to address of last thing you changed" would be better.

**Comment by 42Bastian** [comment]
This leads to a kind of diff between two versions of the project. Maybe a second tool which takes two 6502bench project files to compare them?

**Comment by fadden** [comment]
Moved to https://github.com/fadden/6502bench/wiki/TO-DO-List

**Comment by fadden** [comment]
Added "go to last change" in v1.5.  I found that I often want to see the effects at my current position rather than at the first line of the change, so I'd rather not jump there automatically.
