### ISSUE TITLE
Doc: Description of symbol table format missing/Export 

### ISSUE THREAD

**Issue by 42Bastian** [fadden/6502bench#27]
The symbol window allows import but (I cannot find/there is no) description of the format of import file.
Also, exporting the (visible) symbols will help if multiple files might use the same symbols (like jump table, OS entry or HW addresses).

Edit: Reading the source helps to find out about the format, but export would be nice no matter.

**Comment by fadden** [comment]
For platform stuff like OS entry points and HW addresses that are applicable to lots of projects and lots of users, you would create a .sym65 file in the RuntimeData directory and submit it to the project.  The format is described in the [README for that directory](https://github.com/fadden/6502bench/tree/master/SourceGen/RuntimeData), which is included in the distribution.

The global symbol import/export stuff is for individual projects that are spread across multiple binaries.  The current system is described in the [Advanced Topics](https://github.com/fadden/6502bench/blob/master/SourceGen/RuntimeData/Help/advanced.html) section of the user manual.  (You "import" the other project file to get the global symbols out. There is no feature for dumping the symbol list to a file.)

One area that I'm realizing isn't well explained is creating a .sym65 for an individual project.  You can, however, find an example of this in the [Amper-fdraw](https://github.com/fadden/6502bench/tree/master/SourceGen/Examples/A2-Amper-fdraw) project, which calls into a library that isn't part of the example.

There's currently an item on the [TO DO List](https://github.com/fadden/6502bench/wiki/TO-DO-List), "improve support for sharing exported symbols".

All of the docs were updated for alpha3, but if you've cloned the repository then you've got all the latest stuff anyway. :-)
