### ISSUE TITLE
Figure out Ctrl+W

### ISSUE THREAD

**Issue by fadden** [fadden/6502bench#29]
In the current application, you can format a value as a 16-bit word by:

 1. Select two bytes
 2. Actions > Edit Operand
 3. Click on 16-bit little-endian numeric
 4. Click OK

That's a lot of steps.  This is ameliorated by the ability to select a large number of bytes and apply the format to multiple pairs all at once, but it would be nice to have a keyboard shortcut for this.  We need to decide how to activate it, and whether it's a "set", "toggle", or "rotate" operation.

**Activation**

We'd like this to work in a way that allows 24-bit words (and maybe 32-bit words) as well.  There are a couple of ways to do this:

 1. Require full selection.  You can select 2, 3, or 4 consecutive bytes to indicate the word size.
 2. An alternate approach is to ignore everything but the first selected byte -- the option will do nothing if more than one line is selected -- and grab the next bytes automatically. Key modifiers are used to specify how many: Ctrl+W grabs 2 bytes, Ctrl+Shift+W grabs 3, Ctrl+Shift+Alt+W grabs 4.

Option (1) is the easiest, but perhaps the least convenient, since if the 2nd or later bytes are part of something larger (like an auto-detected string), you have to break it apart before you can select it.

Option (2) requires looking ahead to see if the next byte or three can be word-ified.  We can pull bytes out of auto-generated strings, but if we steal the first byte from a user-specified string we effectively kill the string.  The usual data-edit rules apply, e.g. we're not allowed to straddle a user-specified label or multi-line comment.  There is some risk of creating a UI that appears to behave inconsistently, because sometimes the word op just won't do anything.

**Operation**

If you word-ify two unformatted bytes, things are pretty simple.  If they already have a format, the existing format will be cleared, potentially affecting multiple bytes if it was a string, dense hex, or multi-byte numeric.

If the two bytes were already formatted as a 16/24/32-bit little-endian hex value, we have some options:

 1. Don't do anything.  You wanted a word, it's a word.
 2. Toggle.  Change the bytes back to "default" format.
 3. Rotate.  Numeric words and address words are both very common.  The first use could set it to a 16/24/32-bit hex value, the second could set it to a 16/24/32-bit address (numeric reference), the third could set it back to default.

**Other Notes**

I'm being a little cautious here because this is the sort of thing that quickly becomes part of the workflow, so changing the way it works later is very disruptive (and leads to a proliferation of "Ctrl+W does XYZ" options in the settings).  Getting it right the first time would be nice.

**Comment by mstr-** [comment]
1 vs 2: You should be able to either define one word, or if you have an active selection, convert it all to words.

Also regarding keybinds, just look how ida does it. :)

**Comment by llandyw** [comment]
Just a comment regarding using Ctrl-W.  This might be a problem as Ctrl-W is a very commonly used shortcut for closing the current window/tab.  All MS applications use it as well as all browsers I'm aware of.

Just something to consider.

**Comment by fadden** [comment]
Where it ended up:

 - Not a toggle.  Just changes two bytes to one 16-bit word.
 - Only does 16-bit words, for now.
 - Does not steal bytes from multi-byte items.  You can't Ctrl+W a string.  Use Ctrl+D to make auto-generated strings and .FILLs disappear.
 - If multiple bytes are selected, there must be an even number of them.  The usual region-splitting rules apply, e.g. if there's a .ORG between two bytes you can't convert them into a single word.
 - If the selection is just one byte, the following byte is grabbed automatically (subject to the usual region-splitting rules).

I think this is the simplest useful form of the feature.
