### ISSUE TITLE
ReferenceEquals can be simplified, not really an issue, just information

### ISSUE THREAD

**Issue by llandyw** [fadden/6502bench#30]
I see a couple places where ReferenceEquals(reference, null) type of statement is made.

This can be simplified to   a is null  which would be faster since there's no function/method call to make.

**Comment by fadden** [comment]
According to https://stackoverflow.com/a/735574/294248:

> [Q] Is there extra overhead in using the object.ReferenceEquals method?
> 
> No. The method directly contains the minimal IL description to perform the reference equality check (for the record: it's equivalent to VB's Is operator) and will often be inlined by the JIT (especially when targeting x64) so there's no overhead.

Looking at the other answers and comments there, it appears that as time went by (and machines moved from x86 to x64), the likelihood of inlining and difference in performance between "==" and ReferenceEquals on a class without overloads went from "negligible but measurable" to "none".

The pattern-matching "is" stuff was added in C# 7 ([see blog post](https://blogs.msdn.microsoft.com/dotnet/2017/03/09/new-features-in-c-7-0/)). I had Visual Studio get weird on one of the other C# 7 features (declaring "out" args inside the method call) in some of the libraries.  I'm not quite sure what's up with that, but it has discouraged me from rushing toward C# 7 features.
