### ISSUE TITLE
Simplification (again), default values

### ISSUE THREAD

**Issue by llandyw** [fadden/6502bench#36]
Another item that's useful.  In DisplayList.cs, there are two members.

```
            public Line(int offset, int span, Type type)
            {
                FileOffset      = offset;
                OffsetSpan      = span;
                LineType        = type;
                SubLineIndex    = 0;
            }

            public Line(int offset, int span, Type type, int subLineIndex)
            {
                FileOffset      = offset;
                OffsetSpan      = span;
                LineType        = type;
                SubLineIndex    = subLineIndex;
            }
```

These two can be made into a single member as shown below.

```
            public Line(int offset, int span, Type type, int subLineIndex = 0)
            {
                FileOffset      = offset;
                OffsetSpan      = span;
                LineType        = type;
                SubLineIndex    = subLineIndex;
            }
```
Defaults are nice to have.  I've avoided c++ except for system level stuff, so don't even know if it supports the default parameters of not.

**Comment by fadden** [comment]
For constructors I usually prefer chaining:

            public Line(int offset, int span, Type type) : this(offset, span, type, 0) { }

            public Line(int offset, int span, Type type, int subLineIndex) {
                FileOffset = offset;
                OffsetSpan = span;
                LineType = type;
                SubLineIndex = subLineIndex;
            }

This is a standard Java pattern, as there's no other way to do it in Java.  For this specific example the default parameter approach is cleaner, but if additional varieties of constructor were added that could get murky.

There's some odd cases w.r.t default parameters and polymorphism, but that doesn't apply here.
