### ISSUE TITLE
creating byte table data

### ISSUE THREAD

**Issue by robjustice** [fadden/6502bench#42]
Is there a way to set data in a block of bytes type format?

I have some font data (or just binary data) and I want to layout it out in chars, eg, 8 bytes on each line like this to save space in the source code and let it be commented nicely.

eg:
   .byte $00,$11,$22,$33,$44,$55,$66,$77   ;char1
   .byte $00,$11,$22,$33,$44,$55,$66,$77   ;char2
   .byte $00,$11,$22,$33,$44,$55,$66,$77

**Comment by fadden** [comment]
Select the range of bytes, Actions > Edit Operand, and select "dense hex".  It shows up as ".bulk" in the on-screen listing, but for cc65 it turns into .byte statements.

If the selection won't fit on a single line when formatted, it will be split into multiple lines.

To do what you describe, you'd select 8 bytes, format them, and then add an end-of-line comment. Repeat for the next 8 bytes.

**Comment by fadden** [comment]
I've added it to the ["to do" list](https://github.com/fadden/6502bench/wiki/TO-DO-List).
