### ISSUE TITLE
Support for SOS system calls

### ISSUE THREAD

**Issue by robjustice** [fadden/6502bench#44]
Support for decoding SOS system calls would be nice to have. 

These are very similar to ProDOS MLI calls that you have included support for. For SOS, it uses a BRK instruction instead of a JMP instruction and the byte following the opcode is the SOS system call number. It then has a word pointing to the parameter block like Prodos.

00962B  1  00 C8                   brk  OPEN
00962D  1  6C 94                    .word L946C     ;address to param block

**Comment by fadden** [comment]
Somehow I've managed to go all this time without knowing that SOS worked that way. :-)

Should be straightforward.

**Comment by fadden** [comment]
Wasn't entirely straightforward, but it seems to work.  Looks like this:

```
8b97: 00                 brk
8b98: c4                 .dd1    SOS_GET_FILE_INFO
8b99: e86d               .dd2    L6DE8
8b9b: f006               beq     L8BA3
8b9d: 00                 brk
8b9e: cb                 .dd1    SOS_WRITEFILE
8b9f: f76d               .dd2    L6DF7
8ba1: f032               beq     L8BD5
8ba3: 205a7c    L8BA3    jsr     L7C5A
```

It would be nicer if it read "brk SOS_GET_FILE_INFO", but neither ca65 nor 64tass allow you to write BRK with an operand.  I had been treating BRK as a two-byte instruction, but very few other things do, so I finally gave up and made it a single byte.  (I might be able to jimmy the Merlin 32 code generator into merging lines, but I haven't looked at it.)

If you want to give it a try, I [created a release](https://github.com/fadden/6502bench/releases/tag/v1.3.0-dev1) with the new features.

This is enabled by default for all new Apple /// projects.  If you have an existing Apple /// project, you would need to:

 * Edit > Project Properties
 * Click on Extension Scripts
 * Click "Add Scripts..."
 * In the Apple folder, select SOS.cs

Assuming you already have Apple/SOS.sym65 in the Symbol Files list, that should get the proper inline handling.

To avoid turning every BRK into an OS call, I only treat it as a call if the function code has a symbol defined in SOS.sym65 (which was written by @david-schmidt).

**Comment by robjustice** [comment]
I'm glad you know now about SOS using the BRK instruction :-). I assume when Apple developed Prodos from Sos that the use of this was hard to work in with the existing Apple II rom code. That was also interesting to read about your battle with one byte implementations of the BRK instruction with assemblers.

I downloaded the release above and tried it out. Thanks also for including the steps on updating an existing project, that worked well. The existing project was a SOS interpreter file for Business Graphics that I'm digging into. 

It works very nicely, that will save a lot of time as previously i have had to run through these SOS calls and manually adjust them. Now all I need to tidy up are the parameter blocks.

Thanks!

**Comment by fadden** [comment]
I got ACME cross-assembler support mostly working yesterday, and determined that it also regards BRK with an operand as an error.  Merlin 32 might be the only cross-assembler that supports it.

I think the proper way to make the output look nice is to have SourceGen emit macros (for this, ProDOS, GS/OS, IIgs toolbox, etc), but that's a much broader change.

Glad to hear it's working!

**Comment by fadden** [comment]
A put two-byte BRKs back in (now a project property setting).  I also fixed some stuff in the SOS function definitions.
```
8b94: 20 75 8c              jsr     L8C73+2
8b97: 00 c4                 brk     SOS_GET_FILE_INFO
8b99: e8 6d                 .dd2    L6DE8
8b9b: f0 06                 beq     L8BA3
8b9d: 00 cb                 brk     SOS_WRITEFILE
8b9f: f7 6d                 .dd2    L6DF7
8ba1: f0 32                 beq     L8BD5
```
