### ISSUE TITLE
[QoL] Custom keyboard shortcut for Set Address

### ISSUE THREAD

**Issue by Michaelangel007** [fadden/6502bench#54]
In the main disassembly view there is no keyboard shortcut for `Set Address`.

Notes:

* Ctrl-A can't be used as it is used for `Edit > Select All`
* Ctrl-O can't be used as it is used for `Edit Operand`

Larger issue: Missing custom keyboard shortcuts for the disassembly window.

**Comment by fadden** [comment]
Double-clicking in the address column opens the dialog.  I didn't give it a shortcut because it's relatively rarely used.  This seems like another place where having a keyboard shortcut editor would be handy.

**Comment by fadden** [comment]
Migrating feature requests to [wiki](https://github.com/fadden/6502bench/wiki/TO-DO-List).
