### ISSUE TITLE
[QoL] Custom keyboard shortcut for Inline Data

### ISSUE THREAD

**Issue by Michaelangel007** [fadden/6502bench#58]
The keyboard shortcut for `Actions` > `Hint as Inline Data` is extremely cumbersome to press with a single left hand and requires two hands.  This is annoying because the right hand is usually on the mouse.

Possible ideas:

* `Ctrl-2` (The `@` is a visual mnemonic for data) <-- First choice
* `Ctrl-Q`

**Comment by fadden** [comment]
Migrating feature requests to [wiki](https://github.com/fadden/6502bench/wiki/TO-DO-List).
