### ISSUE TITLE
[QoL] Hide invalid opcodes in 65xx Instruction Chart

### ISSUE THREAD

**Issue by Michaelangel007** [fadden/6502bench#60]
`Tools` > `65xx Instruction Chart` lists all opcodes sorted by byte which is fantastic with invalid opcodes greyed out.  However, there should be a checkbox at the bottom that lets me hide invalid opcodes:

* `[x] Show invalid instructions`

Additionally, another Boolean column named  `Valid` would let me sort these by invalid ones first/last, or valid one first/last.

**Comment by fadden** [comment]
Exclusion checkbox added.  I'm undecided about adding another column.

**Comment by Michaelangel007** [comment]
👍 Verified fixed.

![fixed_59](https://user-images.githubusercontent.com/7876796/74854353-1372a600-52f4-11ea-816c-29f72d605257.png)

I'm happy with you punting on the `Valid` column for now.  (Can always add it later such as the 2.0 low-priority wishlist if anyone else requests it.)  I'll actually "move" the `Valid` column to a new issues as there is another OPTIONAL low-priority feature for the Instruction Chart that I just thought of.
