### ISSUE TITLE
[QoL] 65xx Instruction Chart doesn't have hex input or find

### ISSUE THREAD

**Issue by Michaelangel007** [fadden/6502bench#61]
The `Tools` > `65xx Instruction Chart` doesn't have hex input. I want to be able to enter in a 2-hex digit opcode and have the cursor jump to the appropriate opcode.

Additionally, `Ctrl-F` should pop-up a Find dialog so I can search by mnemonic for those rarely used instructions when I can't remember the opcode.

**Comment by fadden** [comment]
For mnemonics, my assumption was that users would click on a column header to sort and then scroll.  That way you can see all possible addressing modes for the operation in question.  Otherwise it also needs a "find next" so one can iterate through the variations.

**Comment by Michaelangel007** [comment]
I see I'm not the only one who has resorted to sorting by column headers as a work-around. =P

**Comment by fadden** [comment]
Migrating feature requests to [wiki](https://github.com/fadden/6502bench/wiki/TO-DO-List).
