### ISSUE TITLE
[QoL] Smart Go To in Disassembly view

### ISSUE THREAD

**Issue by Michaelangel007** [fadden/6502bench#63]
If the user presses `Ctrl-G` while on a `JSR` instruction in the Disassembly view then the target location should be auto-populated with the with symbol name or address.

# Default

* ![default_goto](https://user-images.githubusercontent.com/7876796/74749397-f61fd800-521e-11ea-919c-f6690974cd1b.png)

# Smart
* ![smart_goto](https://user-images.githubusercontent.com/7876796/74749400-f7e99b80-521e-11ea-81ef-ccac45820792.png)

**Comment by fadden** [comment]
Double-clicking on the JSR takes you to the target address.  The 4th mouse button (usually a thumb button on the side) navigates back.

**Comment by Michaelangel007** [comment]
Singe-click also highlights the target in cyan! That's a nice touch I need to steal for AppleWin. :-)

**Comment by fadden** [comment]
Ctrl+J jumps directly to operand target.
