### ISSUE TITLE
[QoL] Smart Create Label

### ISSUE THREAD

**Issue by Michaelangel007** [fadden/6502bench#66]
`Actions` > `Edit Operand` > `Create Label` should be "smart." The button should have the hex address appended on the end.

# Default

![default_create_lable](https://user-images.githubusercontent.com/7876796/74750500-a80bd400-5220-11ea-81ba-0e4683884cba.png)

# Smart

*  `Create Label for $817B`

**Comment by fadden** [comment]
It should probably just have a text edit box that's part of the radio button collection.  I re-used the Edit Label dialog because it saved some code, but it'd save some clicking around (and some accidentally typing stuff into the Symbol box) if it were just a text field.

**Comment by fadden** [comment]
Migrating feature requests to [wiki](https://github.com/fadden/6502bench/wiki/TO-DO-List).
