### ISSUE TITLE
[QoL] Smart String

### ISSUE THREAD

**Issue by Michaelangel007** [fadden/6502bench#70]
In the disassembly window with raw bytes selected pressing a new hotkey -- proposed `Ctrl-4` from #69 -- would function as `Hint as Data String` (or even `Hint as String`.)

This would tag/hint the data as a string.

Additionally the last byte should be checked to see if it is null and would automatically have `Edit Operand` default to `Null-terminated string` in this case.

**Comment by fadden** [comment]
Migrating feature requests to [wiki](https://github.com/fadden/6502bench/wiki/TO-DO-List).
