### ISSUE TITLE
[QoL] Custom keyboard shortcut for Smart Navigate

### ISSUE THREAD

**Issue by Michaelangel007** [fadden/6502bench#72]
In the disassembly view when the selected line is on a `JSR` / `JMP` instruction the `Navigate` > `Nav Forward` (Alt-Right) menu option is disabled.

Since `->` is used to scroll the window other keys must be used:

Ideally, there should be "Smart Navigate" (or two keys) when viewing a 6502 function jump table with that stupid -1 bug.

* `TAB` <-- First choice
* `Alt` + `->` Smart Jump to Address <-- First choice
* `Shift`  + `->` Jump to address
* `Ctrl` + `->` Jump to Address+1

I see that I need to update AppleWin's navigation. :-)

**Comment by fadden** [comment]
The forward/backward navigation are from a stack that gets added to as you jump around (with goto or by double-clicking on something).  It's not affected by what is selected.  Double-click on the opcode to jump to whatever the operand is referring to.

**Comment by Michaelangel007** [comment]
That's a nice workaround until there is keyboard shortcut. Thanks!

**Comment by fadden** [comment]
Ctrl+J jumps directly to operand target.
