### ISSUE TITLE
[QoL] Bookmarks

### ISSUE THREAD

**Issue by Michaelangel007** [fadden/6502bench#73]
AppleWin's debugger let's you set bookmarks (`Ctrl-Shift-#`) and quickly jump back to them (`Ctrl-#`)

Ideas:

* Ctrl-5 Goto bookmark 1
* Ctrl-6 Goto bookmark 2
* Ctrl-7 Goto bookmark 3
* Ctrl-8 Goto bookmark 4
* Shift-5 Set bookmark 1
* Shift-6 Set bookmark 2
* Shift-7 Set bookmark 3
* Shift-8 Set bookmark 4

**Comment by fadden** [comment]
The current bookmark mechanism is Notes, which gives you a color-coded list in the bottom-left window.  Were you envisioning these as session-specific, i.e. they don't get saved in the project file?

**Comment by Michaelangel007** [comment]
Notes in the bottom left are great.  I prefer keyboard shortcuts so I don't have to keep moving the mouse down, click, and move it back.

**Comment by fadden** [comment]
Migrating feature requests to [wiki](https://github.com/fadden/6502bench/wiki/TO-DO-List).
