### ISSUE TITLE
[QoL] Visualizer New Bitmap dimensions are too restricting

### ISSUE THREAD

**Issue by Michaelangel007** [fadden/6502bench#74]
_Lode Runner_ has its sprites/font data located at $AD00 .. $B5EF.  This is how it is supposed (*) to look inside the visualizer:

![visualizer_lode_runner_bitmap](https://user-images.githubusercontent.com/7876796/74758258-f2df1900-522b-11ea-9fe8-997f1555d0e3.png)

Unfortunately it is not possible to view them unless you manually view them individually which is 
_extremely_ time consuming to add bitmaps.  Compounded by no keyboard shortcut to add `New Bitmap` (Issue #56)

The problems are:

* The visualizer artificially restricts dimensions to confirm to Apple's native display limits which normally would be fine except when it isn't, and
* The visualizer is a missing Glyph stride which needs to be negative.

The font data is packed in a unoptimized format:

| Glyph | Scanline | Byte 0 | Byte 1 |
|:--|:--|:--|:--|
| 0 | 0 | AD00 | AD68 |
| 0 | 1 | ADD0 | AE38 |
| 0 | 2 | AEA0 | AF08 |
| ... | ... | ... | ... |
| 0 | A | B520 | B588 |
| 1 | 0 | AD01 | AD69 |
| 1 | 1 | ADD1 | AE39 |
| ... | ... | ... | ... |
| 1 | A | B521 | B589 |
| 103 | 0 | AD67 | ADCF |
| 103 | 1 | AE37 | AE9F |
| ... | ... | ... | ... |
| 103 | A | B587 | B5EF |

# Font Metrics

* Cell Size: 10 px x 12 px
* Column Stride: 104 bytes
* Row Stride: 0 bytes
* Glyph Stride: -2287  (-$8EF)

That -2287 comes from:

* Start of Sprite 0 = $AD00
* End of Sprite 0 = $AD00 + 2*$B*$68 = $AD00 + $8F0 = $B5F0
* Start of Sprite 2 = $AD01
* Delta = $AD01 - $B5F0 = - $8EF

Here is an AppleWin debugger script to unpack the second glyph `TILE_BRICK` (since the first glyph is `TILE_AIR`)

```
// Glyph 1
4016<AD01.AD01M
4017<AD69.AD69M
4018<ADD1.ADD1M
4019<AE39.AE39M
401A<AEA1.AEA1M
401B<AF09.AF09M
401C<AF71.AF71M
401D<AFD9.AFD9M
401E<B041.B041M
401F<B0A9.B0A9M
4020<B111.B111M
4021<B179.B179M
4022<B1E1.B1E1M
4023<B249.B249M
4024<B2B1.B2B1M
4025<B319.B319M
4026<B381.B381M
4027<B3E9.B3E9M
4028<B451.B451M
4029<B4B9.B4B9M
402A<B521.B521M
402B<B589.B589M
```

That was a snippet created via this short C meta-program:

```c
    int dst    = 0x4000; // Default to HGR page 2
    int stride =   0x68; // Column Stride

    for( int glyph = 0; glyph < stride; ++glyph )
    {
        int addr = 0xAD00 + glyph;// Font Data $AD00 .. $B5EF

        printf( "// Glyph %d\n", glyph );
        for(  int y = 0; y < 0xB; ++y ) // Font height is 12 scan lines
        {
            printf( "%04X<%04X.%04XM\n", dst, addr, addr ); addr += stride; dst++;
            printf( "%04X<%04X.%04XM\n", dst, addr, addr ); addr += stride; dst++;
        }
        printf( "\n" );
    }
```

This is the TLC that the visualizer bitmap needs:

* Width needs to be larger then 40. 1024 Should be a safe limit.
* Height is limited to 192. This needs to be increased to 2048.
* Row stride can't be negative <-- not used in this case but might be for other games
* Glyph stride can't be negative
* Missing the option to allow data to extend bitmap data past the EOF.

```
[x] Allow data past End-of-file
    [00] Fill with
```

**Comment by Michaelangel007** [comment]
Here is the unpacked font for _Lode Runner_ for reference:

[font_unpacked.zip](https://github.com/fadden/6502bench/files/4220652/font_unpacked.zip)

**Comment by fadden** [comment]
The hi-res bitmap visualizer is intended for a single bitmap.  This is really multiple bitmaps, so the hi-res font visualizer might be a closer fit for this, and has the useful property of displaying bitmaps in a grid with transparent pixels separating individual item.  (On the other hand, if you made them individual bitmaps, you could generate animated GIFs.  There's nothing stopping you from creating multiple visualizations for the same data, or placing them at arbitrary positions in the file, so...)

We could add some options to the font visualizer, or define a new "bitmap grid" visualizer (fonts get embedded pretty often, so I'd like to keep that simple).  At some point it makes more sense to just take the standard visualizer and customize it for a specific project, but this seems like it will yield to sufficient parameterization.

The width/height limits are arbitrary.  They're defined in the runtime-compiled extension script, so that much is easy to change.

**Comment by Michaelangel007** [comment]
Some context on the motivation.  Having it built into the visualizer lets me skip having to write custom code to display a sprite sheet.

i.e.
* Fire up Lode Runner inside AppleWin
* Press `F7` at the main logo screen
* Run this script in the debugger

```
7C3B:4C 03 B6 // JMP patch
B600:4C CE 86 // JMP $86CE
B603:C9 DA    // CMP $'Z'
B605:D0 F9    // BNE $B600
B607:A9 00    // LDA #00
B609:85 85    // STA zCursorX
B60B:85 86    // STA zCursorY
B60D:8D FF B6 // STA B6FF
B610:AD FF B6 // LDA B6FF
B613:C9 68    // CMP #$68
B615:F0 11    // BEQ $B600
B617:20 77 7B // JSR DrawGlyphPage2
B61A:EE FF B6 // INC $B6FF
B61D:A5 85    // LDA zCursorX
B61F:C9 10    // CMP #$10
B621:D0 ED    // BNE $B610
B623:20 7D 7B // JSR _PrintCharCR
B626:F0 E8    // BEQ $B610 always
B628:8D 55 C0 // STA page2
B62B:AD 00 C0 // LDA keyboard
B62E:10 FB    // BPL $B62B
B630:8D 10 C0 // STA keystrobe
B633:8D 54 C0 // STA page1
B636:30 C6    // BMI $B600
```

* Press `F7` to return to the game
* Press `Ctrl-E` to enter the editor
* Press the new command `Z` to display the sprite sheet.
* Profit!

**Comment by Michaelangel007** [comment]
A new drop-down for `Apple ][ Sprite Sheet` is perfectly fine.

**Comment by fadden** [comment]
Try this: [sprite-test.zip](https://github.com/fadden/6502bench/files/4222481/sprite-test.zip)

Tested with a Lode Runner extract and the two sets of digits from Space Eggs, as well as a font in an existing project.  The .cs should work with 1.5, so you can drop that into your RuntimeData/Apple directory.

**Comment by fadden** [comment]
![Untitled](https://user-images.githubusercontent.com/6185696/74791744-33f91c80-5270-11ea-918d-e2cacc628a18.png)

Note row stride can be left as zero, because the default is col stride * cell width.
