### ISSUE TITLE
[QoL] Visualizer Bitmap missing high-bit palette control

### ISSUE THREAD

**Issue by Michaelangel007** [fadden/6502bench#76]
The visualizer is missing a checkbox that adds user control of the high-bit for Apple ][ graphics:

`[x] High-bit set. This palette bit controls green/magenta (off) orange/blue (on)`

**Comment by fadden** [comment]
Most things that want the high bit to be set will set it in the bitmap data itself.  I take it you've found a counter-example?

**Comment by Michaelangel007** [comment]
Yeah, _Lode Runner_ has all of its sprite data @ $AD00 with the low bit set.  It uses "Colorization Tables" at @ $A200, $A280, $A300, ... $A8FF to colorize the monochrome pixels. See #74 for details.

```
Column2Pixel .dd1 $a2
         .dd1    $a3
         .dd1    $a4
         .dd1    $a5
         .dd1    $a6
         .dd1    $a7
         .dd1    $a8
```

I haven't (yet) seen the reverse of the high-bit being forced off, but might need to consider that edge case as well.

**Comment by Michaelangel007** [comment]
_Lode Runner_ **isn't** the only game.  I've seen others but their names escape my memory at the moment.  i.e. Font Data.

**Comment by fadden** [comment]
Would this make the most sense as a "flip high bit"?  Seems like it works for the case of "all bits are low and should be set".  I'm wondering what it means if something has high bits set, or has some bytes each way.

**Comment by Michaelangel007** [comment]
That might work.  There are a couple of different ways of handling this:

* `Force high bit.`
* `Force low bit`
* `Toggle high bit`

Sadly we need more data before we can make an informed choice that covers all cases (instead of just the common ones.)

**Comment by fadden** [comment]
Did the "flip bit" thing.  Anything fancier should probably use a custom converter that knows how to set the bits correctly for each byte.

**Comment by Michaelangel007** [comment]
👍 Verified fixed.

![fixed_76](https://user-images.githubusercontent.com/7876796/74854158-cbec1a00-52f3-11ea-8bc2-cc5adbdcef85.png)

As I reverse engineer more games I'll make notes of any failing edge cases.
