### ISSUE TITLE
[QoL] Export to AppleWin's Debugger

### ISSUE THREAD

**Issue by Michaelangel007** [fadden/6502bench#77]
AppleWin has several debugger commands to allow the debugger to mark up data instead of interpreting it as code. Ideally we could export the disassembly as a plain-text file to be fed into the debbugger.

There are 3 sections of the export:

* Raw text dump. `addr: byte1 byte2 byte3 ...`
* Symbol names. `sym <Name> = <Addr>`
* Data regions (tells the debugger to not interpret as code but display as inline data)
  * Raw bytes: `db <name> <addr>`
  * Raw pointers: `da <addr>`
  * TEXT. `ASC <start>:<end>`
  * Sprites -- I have the foundation of this in AppleWin but it is still incomplete.

AppleWin's TODO:
* Need to look into how well `.ORG $####` is supported in the debugger.
* pseudo-directives starting with period need to be ignored on the command line
* Need to add support to the debugger command line to ignore text past the semi-colon.  (Should have never used the C++ `//` double forward slash comment and used the proper  `;` assembly comment from the beginning.)

**Comment by fadden** [comment]
There are currently 3 export options (HTML, text, CSV), in addition to the cross-assembler code generation.  I was expecting to add a symbol export at some point.  Hadn't thought about providing type info.

Seems like you want a list of {address,label} pairs, and then a list of {start,length,type} tuples if you want to define what's code vs. raw data vs. text vs. graphics.

**Comment by Michaelangel007** [comment]
The list of 2D and 3D tuples would be a great start!

I assume I'll have to munge the data to be script-ready but tweaking is to be expected.

**Comment by fadden** [comment]
Migrating feature requests to [wiki](https://github.com/fadden/6502bench/wiki/TO-DO-List).
