### ISSUE TITLE
Unable to build with Visual Studio 2019 Community

### ISSUE THREAD

**Issue by Michaelangel007** [fadden/6502bench#78]
The build instructions [6502bench/SourceNotes.md](https://github.com/fadden/6502bench/blob/master/SourceNotes.md) unfortunately doesn't list which version of .NET is needed to build.

I've installed [Visual Studio 2019 community](https://visualstudio.microsoft.com/downloads/) and after converting ...

![migration](https://user-images.githubusercontent.com/7876796/74804073-fc9c6700-5293-11ea-9db7-abb4b8994982.png)

... `Build` > `Build Solution` gives the following error:
```
6502bench\PluginCommon\PluginCommon.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.
```

The installed .NET is the [latest](https://dotnet.microsoft.com/download/visual-studio-sdks)
```
C:> dotnet --list-sdks
3.1.102 [C:\Program Files\dotnet\sdk]
```

Extra info:

```
C:>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.102
 Commit:    573d158fea

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.102\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  3.1.102 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

`Build` > `Clean` fails as well.

This is the version of VS installed:

![vs2019_about](https://user-images.githubusercontent.com/7876796/74803968-a3ccce80-5293-11ea-89bf-164affee94f5.png)

**Comment by Michaelangel007** [comment]
Looks like .NET 2.0 is no longer available, only `.NET Core 2.1 LTS Runtime` which automatically installs `.NET Core 3.1 SDK`

![dotnet_2 1](https://user-images.githubusercontent.com/7876796/74850137-73fee480-52ee-11ea-8a00-93b76c6633bf.png)

Installing that fixes the previous error of `Microsoft.NET.Sdk`. I can now see ALL the solution files  (WOOT)  ...

![solution_project_files_visible](https://user-images.githubusercontent.com/7876796/74851027-89284300-52ef-11ea-84e2-06c859ea4926.png)

... but gives a new build error (ARGH).

`C:\Program Files\dotnet\sdk\3.1.102\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(234,5): error NETSDK1004: Assets file '6502bench\CommonUtil\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.`

Selecting `Project` > `Manage NuGet Packages...` shows this dialog error:

![Project_Manage_NuGet](https://user-images.githubusercontent.com/7876796/74850353-bd4f3400-52ee-11ea-9fcf-784243bfcca2.png)

Clearing the cache under `Tools` > `Options` > `NuGet Package Manager` > `General` > `Clear All NuGet Cache(s)` doesn't help.

Selecting a new C# Project doesn't list any templates -- which is weird.

![new_csharp_project](https://user-images.githubusercontent.com/7876796/74850650-18812680-52ef-11ea-8919-7e863200c622.png)


I'll see if there any optional packages I need to install with the MSVC 2019 Installer.

Could you share a cpicture of your installer's settings for `Workloads` and `Individual components` ?

**Comment by Michaelangel007** [comment]
Success!

```
========== Build: 7 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========
```

It helps if one actually installs `.NET desktop development` :-)

![required_workloads](https://user-images.githubusercontent.com/7876796/74852023-e670c400-52f0-11ea-8287-c7498eafe779.png)

This is what the Solution looks like now:

![solution_with_sdk_installed](https://user-images.githubusercontent.com/7876796/74852237-26d04200-52f1-11ea-8649-2764c7648d4c.png)

I'll add these images to the [SourceNotes](https://github.com/fadden/6502bench/blob/master/SourceNotes.md) so people know exactly what they need to install later in the week.

**Comment by fadden** [comment]
IIRC .NET Core is a superset of .NET Common.  I've been sticking with the older interface definitions to have the best chance of working on older systems like Win7.
