### ISSUE TITLE
Special handling for PRG header

### ISSUE THREAD

**Issue by fadden** [fadden/6502bench#90]
Some executable binaries begin with a header that is parsed by the operating system but not actually loaded into memory.  The header is generally added by the assembler or linker, and is not part of the source file (or, if it is, it takes the form of assembler/linker directives).

A very common example of this is the two-byte header on C64 PRG files, which holds the load address of the executable.  The address is generated by the assembler, based on the address of the first byte of the file.

There are three things to consider:

 * How the feature is enabled.
 * How it looks on-screen.
 * How it's communicated to the assembler.

### Enabling ###

The simple answer is to make it a boolean project property.  "Is PRG file" or something equally blatant.  The initial value would be determined by the `first-word-is-load-addr` property from the system definitions file.

The property would be implicitly disabled if the address of the first byte in the file doesn't match the value stored in the file.  This is necessary because SourceGen is required to generate code that reproduces the original binary file.

Because we're omitting the line, we will generate broken code if the line has a label, even if it's auto-generated.  So we either need to prevent labels from being placed there, or disable the feature if a label is added.

### Display ###

The header is part of the file, and hiding parts of the file seems like a bad policy.  There's also a fundamental assumption that any file offset can be mapped to an address, so there's no way to declare the bytes as being un-addressable.

The current implementation of `first-word-is-load-addr` sets the initial address to start-2, and generates a redundant .ORG at offset +000002 to emphasize that it's the real start of the file.  If we don't want to hide the bytes, and we have to give them an address, we can't do much better here without adding a new way to display file headers.

It might be sufficient to suppress the initial .ORG statement.  (It's still there, you just can't see it.)

We could also replace the .DD2 directive with something made up (".PRG" or "PRG-HDR") to make it more obvious.  There's nothing stopping the user from reformatting the two initial bytes, though, so we either need to add special-case code in the editor to prevent it from changing, or ensure that the display code doesn't alter the directive string if it has been changed.

### Output ###

The currently-supported cross-assemblers handle PRG files in different ways:

 * 64tass: the header is added by default (`--cbm-prg`), and must be explicitly disabled if not desired (`--nostart`).
 * cc65: the .cfg file specifies a two-byte `LOADADDR` segment.
 * ACME: the header is added if the output filename ends with ".prg".
 * Merlin 32: no PRG support.

Of these four, only cc65 is 100% reliable, because all necessary information is contained in the output (we generate custom .cfg files).  For 64tass, we can do it correctly within SourceGen, but it's up to the user to supply the correct set of command-line options when building it elsewhere.  (This is always the case, but we're creating a situation where some SourceGen projects require one set of options, and other projects require a different set of options, e.g. if you have disassembled a data file to take advantage of the visualizers.  This may cause confusion.)

ACME will only work with the correct output file name, and I'm reluctant to force that.  We can take the opposite approach, and only strip the header if we know the output file will end with ".prg", but when running the assembler internally we always end filenames with the assembler name (e.g. "_acme") so it won't help there.

In any event, each IAssembler implementation will need to query the project for the state of the PRG flag, and modify the output accordingly:

 * if the assembler has a reliable PRG option, and
 * if the PRG flag is set in the project properties, and
 * if the address of offset +000002 is equal to the 16-bit value at +000000, and
 * there is no label at offset +000000 (including auto labels)

then:

 * do whatever steps are necessary to output a PRG header
 * start generating code from offset +000002

Otherwise, we just generate the file in the usual way.

Comments and long comments associated with offset +000000 will be discarded.

**Edit:** this was first raised in issue #23, which inspired the stuff we have now.

**Comment by BacchusFLT** [comment]
Well put! All in favour of course...

**Comment by fadden** [comment]
In the theme of "keep it simple, stupid"...

I'm not sure a PRG flag in the project properties is necessary.  If, at assembly source generation time, we determine that:

 * the file is at least 3 bytes long
 * the format at +000000 is a 16-bit numeric data item (not executable, not two 8-bit values, not a 24-bit value, etc.)
 * the address of offset +000002 is equal to the 16-bit value at +000000
 * there is no label at offset +000000 (including auto labels)

Then, if we're generating code for an assembler that has an emphasis on C64 work (such as 64tass), we might as well treat it like a PRG.  The only value in having a project property is to say "it's not a PRG", but that's very unlikely, and you can accomplish that by formatting the bytes or adding a label.

A similar test could be used to modify the on-screen display, though in that case it may be necessary to have an "off" switch, depending on how much we conceal.  That could be an app setting though ("auto-detect PRG files"), rather than a project property, since it only impacts the display.  (I'm still undecided when it comes to hiding stuff on screen.)

There's no need to examine the `first-word-is-load-addr` system parameter.  The addresses and formatting applied when it's set are what matters.  If the user changes those around, then it's not structured like a PRG file anymore, so the parameter value is irrelevant.

Unrelated but in the neighborhood: I think `--long-address` needs to be omitted for non-65816 code.

**Comment by BacchusFLT** [comment]
Den lör 17 okt. 2020 kl 02:51 skrev Andy McFadden <notifications@github.com
>:

> In the theme of "keep it simple, stupid"...
>
> I'm not sure a PRG flag in the project properties is necessary. If, at
> assembly source generation time, we determine that:
>
>    - the file is at least 3 bytes long
>    - the format at +000000 is a 16-bit numeric data item (not executable,
>    not two 8-bit values, not a 24-bit value, etc.)
>    - the address of offset +000002 is equal to the 16-bit value at +000000
>    - there is no label at offset +000000 (including auto labels)
>
> Then, if we're generating code for an assembler that has an emphasis on
> C64 work (such as 64tass), we might as well treat it like a PRG. The only
> value in having a project property is to say "it's not a PRG", but that's
> very unlikely, and you can accomplish that by formatting the bytes or
> adding a label.
>
> A similar test could be used to modify the on-screen display, though in
> that case it may be necessary to have an "off" switch, depending on how
> much we conceal. That could be an app setting though ("auto-detect PRG
> files"), rather than a project property, since it only impacts the display.
> (I'm still undecided when it comes to hiding stuff on screen.)
>
> There's no need to examine the first-word-is-load-addr system parameter.
> The addresses and formatting applied when it's set are what matters. If the
> user changes those around, then it's not structured like a PRG file
> anymore, so the parameter value is irrelevant.
>
> Unrelated but in the neighborhood: I think --long-address needs to be
> omitted for non-65816 code.
>
Super - agree with both the conclusion on TASSS as assembler is assuming
PRG standard format, and that non-65816 is by definition limited to short
addressing.

**Comment by fadden** [comment]
Try this: https://github.com/fadden/6502bench/releases/tag/v1.7.3-dev2

Implementation is as planned, except:
 - PRG test now also requires an ORG at offset +000002.  Which it should always have, since it's the actual start of the file contents.  I feel better about hiding the initial ORG statement on-screen when I know there's one coming on the next line.
 - There are no app settings or project properties.  The test should be strict enough to avoid false-positives, and you can trivially disable the feature by putting a label at offset +000000.
 - I didn't try to do anything fancy with the .word op at the start of the file.  The only on-screen change is suppression of the initial ORG directive.

Only implemented for 64tass code generation.

I also added a "load address" comment on the first line of new projects.  I don't know if this is useful or just something that everyone will delete immediately.  Feedback welcomed. :-)

This release also includes my changes to the "hint" naming.

**Comment by fadden** [comment]
Any feedback on the PRG feature?

**Comment by fadden** [comment]
Released in v1.7.3.

**Comment by BacchusFLT** [comment]
Den sön 18 okt. 2020 kl 23:00 skrev Andy McFadden <notifications@github.com
>:

> Try this: https://github.com/fadden/6502bench/releases/tag/v1.7.3-dev2
>
> Implementation is as planned, except:
>
>    - PRG test now also requires an ORG at offset +000002. Which it should
>    always have, since it's the actual start of the file contents. I feel
>    better about hiding the initial ORG statement on-screen when I know there's
>    one coming on the next line.
>    - There are no app settings or project properties. The test should be
>    strict enough to avoid false-positives, and you can trivially disable the
>    feature by putting a label at offset +000000.
>    - I didn't try to do anything fancy with the .word op at the start of
>    the file. The only on-screen change is suppression of the initial ORG
>    directive.
>
> Only implemented for 64tass code generation.
>
> I also added a "load address" comment on the first line of new projects. I
> don't know if this is useful or just something that everyone will delete
> immediately. Feedback welcomed. :-)
>
> This release also includes my changes to the "hint" naming.
>
Sorry- took forever to get a slot.

First: Norton hates the CommonWPF.dll and the program silently doesn't
start if it's gone.

Second: The disassembly still has a word in the start that gives the start
of the file. I do well understand that your view is that the start bytes
are part of the file, but the data they represent are part of the ORG you
set on the file row. The load address is the org - that is what the first
org is about.

; 6502bench SourceGen v1.7.3-dev2
>                 .dd2  $0801           ;load address
>                 .org  $0801


This would be highly relevant for a BIN file, but for a PRG file you have
already got the 0801 load address as the .org.

This is what I expect it to look:

; 6502bench SourceGen v1.7.3-dev2
>                 .org  $0801  ;load address


/Pontus

**Comment by fadden** [comment]
On screen it looks like:

```
                   ; 6502bench SourceGen v1.7.3
9ffe: 00 a0                        .dd2  $a000           ;load address

                                   .org  $a000
a000: ff                           .dd1  $ff
```

The 64tass output is:

```
; Target assembler: 64tass v1.53.1515 [--ascii --case-sensitive -Wall]
; 6502bench SourceGen v1.7.3
        .cpu    "6502"
*       =       $a000
        .byte   $ff
```

I do feel that every byte in the file should be visible on screen.  You can double-click on the Bytes column to get a hex dump, but you shouldn't have to hunt around for ways to see what's in the file.  The disassembly process is fundamentally a matter of converting a raw hex dump to human-readable form, so keeping sight of the hex dump makes sense to me.  SourceGen guarantees that the source file generated will assemble to exactly match the original binary, and I think it's less confusing to be able to see the entire binary.  Especially when you start looking at other platforms and non-C64-specific assemblers.

The assembler output can be whatever it needs to be, and is tailored to each individual assembler, so dropping lines from that is straightforward.  64tass has a strong C64 focus, so having it treat PRG files specially makes sense.

I don't know why a virus scanner would have an issue with CommonWPF.dll.  There's nothing very interesting inside it.  It's linked directly into the main program, so I'll blame Windows for the lack of a useful error message.

**Comment by BacchusFLT** [comment]
Andy,

I still think you come from a different place, and it might be that your
point make sense there. But its still alien seen from a c64 perspective.

It might be that other platforms have files that don't have a defined
start, but that is the native format of the C64 that is supported by the
system. You cannot execute a file that doesn't have a startadress unless
you write another program that does it for you. It would be really sad if a
very competent product would be getting such a basic prerequisite wrong and
people would use it for this reason.

The start address IS in the reassembly by setting a start adress. There is
no point in ALSO have it as data. You are presenting it twice. The ORG IS
the representation of the startword. Read in the two bytes and set them as
the ORG - now ALL the binary data is represented in the source. But only
once.

On the C64, if you disassemble a file, the first two bytes are made to the
start adress and then the disassembly is from byte 2.

The aim of reassembling should be to generate source that can be assembled
back to the same binary. The first two bytes were never part of the
original source as a word, that generated the binary. They were an ORG
startment that yielded the two bytes. Reassembled, these two bytes should
convert back to an ORG address. Nothing else.

I still haven't seen any assembler on the C64 that did this any different.

/Pontus
