### ISSUE TITLE
Problem defining variables on the boundary of a stack frame

### ISSUE THREAD

**Issue by ERolfi** [fadden/6502bench#96]
When trying to define the size of the par_address variable, I'm not allowed to cross the boundary of $FF. I should set it to a size of 3 bytes (addr/3) even though I'm accessing all of its 4 bytes in the following subroutine.

Am I doing something wrong here?

Thanks.
```
var_length      .var  $f2    {addr/2}
var_address     .var  $f4    {addr/4}
par_address     .var  $fd    {addr/3}

strlen          phd
                tsc
                sec
                sbc   #$00f7
                tcd
                adc   #$00f0
                tcs
                stz   var_length
@DO             ldx   par_address+2
                lda   par_address
                inc   par_address
                bne   @DONT_INC
                inc   par_address+2
@DONT_INC       sta   var_address
                stx   var_address+2
                lda   [var_address]
                and   #$00ff
                beq   @RETURN_LENGTH
                inc   var_length
                bra   @DO

@RETURN_LENGTH  lda   var_length
                tay
                tdc
                clc
                adc   #$00f7
                tcs
                tya
                pld
                rtl
```

**Comment by fadden** [comment]
It's restricting the range because you're only allowed to address local variables with a direct-page access, but now I see that I failed to take 16-bit accesses into account.  The range check is correctly limiting the address to [$00,$ff], but should be limiting address+width to [$00,$100] instead.  And the maximum width of a local variable is 257, not 256.

**Comment by ERolfi** [comment]
Thank you, that's exactly what I meant.

**Comment by fadden** [comment]
Should be fixed here: https://github.com/fadden/6502bench/releases/tag/v1.7.5-dev2

**Comment by ERolfi** [comment]
-it's ok now, thank you
